### ISSUE TITLE
Supported elements and parameters in s3 rest api

### ISSUE THREAD

**Issue by rom-stratoscale** [scality/S3#1050]
Hey,
Do you have a list of supported parameters and unsupported elements in your s3 implementation?

I'm familiar with this file https://github.com/scality/S3/blob/42bc850f81325c9cbeabdc4e706feb1250456306/constants.js#L82 but that only covers the queries and the headers.

Thanks,
Rom

**Comment by rahulreddy** [comment]
@rom-stratoscale Are you looking for the list of APIs we support?

**Comment by rom-stratoscale** [comment]
@rahulreddy yep.

**Comment by rahulreddy** [comment]
Here's the list of APIs we support so far. I will add it to the README for future reference.

| API Support   |
|----------|
| GET Service |
| DELETE Bucket |
| GET Bucket Versioning |
| GET Bucket Location |
| GET Bucket (List Objects) |
| GET Bucket Object Versions |
| Head Bucket |
| PUT Bucket |
| PUT Bucket Versioning |
| GET Bucket ACL |
| PUT Bucket ACL |
| List Multipart Uploads |
| PUT Bucket Website |
| GET Bucket Website |
| DELETE Bucket Website |
| PUT Bucket CORS |
| GET Bucket CORS |
| DELETE Bucket CORS |
| DELETE Bucket Replication |
| GET Bucket Replication |
| PUT Bucket Replication |
| DELETE Object |
| DELETE Object Tagging |
| DELETE Multiple Objects |
| GET Object |
| GET Object Tagging |
| GET Object ACL |
| HEAD Object |
| PUT Object |
| PUT Object Tagging |
| PUT Object ACL |
| PUT Object - Copy |
| Initiate Multipart Upload |
| Upload Part |
| Upload Part (copy) |
| Complete Multipart Upload |
| Abort Multipart Upload |
| List Parts Multipart Upload |

**Comment by Nissan-Zisken-Stratoscale** [comment]
Do you support all of the request parameters, headers and elements of these APIs as defined in the AWS S3 API documentation?
If not do you have an reference which defines what is or is not supported from each of these three?
Thanks,
Nissan Zisken

**Comment by rahulreddy** [comment]
> Do you support all of the request parameters, headers and elements of these APIs as defined in the AWS S3 API documentation?

Yes, in general. All request parameters and headers that are specific to the implemented APIs should be supported unless it's specified in the exclusion list here https://github.com/scality/S3/blob/42bc850f81325c9cbeabdc4e706feb1250456306/constants.js#L82 .
Which specific request parameter/header are you looking for? Or is there some API not working as it should?

**Comment by Nissan-Zisken-Stratoscale** [comment]
Thank you for the quick turnaround.
I am not looking at a specific parameter/header just trying to understand the delta between Scality S3 APIs and AWS S3 APIs.
Two more general questions, if I may:
1. When you say "All request parameters and headers that are specific to the implemented APIs should be supported unless it's specified in the exclusion list here" does this also include support for the "Request **elements**" specified for each API?
2. Since the exclusion list of unsupported headers does not include any of the Common Request Headers is it fair to assume that Scality S3 supports all of the the Common Request Headers?
Thank you,
Nissan Zisken

**Comment by rahulreddy** [comment]
> When you say "All request parameters and headers that are specific to the implemented APIs should be supported unless it's specified in the exclusion list here" does this also include support for the "Request elements" specified for each API?

Yes, the request elements specified in each api should be fully supported.


> Since the exclusion list of unsupported headers does not include any of the Common Request Headers is it fair to assume that Scality S3 supports all of the the Common Request Headers?

Correct, all common request headers are supported.

We try to be as close to AWS S3 API request/response as possible. So it's fair to assume that whatever worked with AWS S3 would work with CloudServer.

**Comment by Nissan-Zisken-Stratoscale** [comment]
1. Have you added support for additional S3 APIs since last December? If yes, could you please send me the updated list.
2. Do you plan on adding support for additional S3 APIs in the future?
Thanks,
Nissan
