### ISSUE TITLE
Publicly serve files from scality

### ISSUE THREAD

**Issue by gallart** [scality/S3#1052]
### Description

I'm using CloudServer to allow application developers to push user uploads to a S3 bucket. I'm now wondering how I can server these files publicly (using webserver or using CloudServer directly).

### Proposal

Not sure if this is possible/wanted.

### Current behavior

Files only accessible through S3 protocol.

### Desired behavior

Files accessible from HTTP protocol.

### Use case

Direct link to s3 files (for public CDN for example).

**Comment by rahulreddy** [comment]
You can use Object ACLs, `public-read` or `public-read-write`, to set the objects as public. ACLs' reference http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl.

**Comment by gallart** [comment]
You are misunderstanding me @rahulreddy, I mean "direct HTTP access".

So far, I managed to work something out with Nginx.

**Comment by rahulreddy** [comment]
Once you set an object as public, you can access it as
`http://127.0.0.1:8000/<bucket>/<object>`

**Comment by gallart** [comment]
Good to know. Thanks Rahul!
