### ISSUE TITLE
Error 409 MPU in Progress

### ISSUE THREAD

**Issue by jbrusq** [scality/S3#106]
Hi,
AT xxx, user uses Windows  cloudberry to test upload/download.
We faced an issue as one bucket couldn't be removed : "Error 409 (MPU in Progress)".

I don't have any logs.
Is there a procedure to clean the status or to force the deletion of the bucket  ?

Jerome

**Comment by michael-zapata** [comment]
Hello,

You can try to use the mpUpload abort operation: http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadAbort.html

**Comment by GiorgioRegni** [comment]
Yes, you can't remove a bucket as long as there are running operations.
