### ISSUE TITLE
Error: Callback function "bound _call" timed out.

### ISSUE THREAD

**Issue by gallart** [scality/S3#1108]
## Bug report information

Scality S3 drop the following error after startup (despite working nicely) :

```
0|index    | {"name":"MetadataFileClient","time":1517996542124,"error":{"code":"ETIMEDOUT","info":"operation getManifest timed out"},"level":"error","message":"Error fetching manifest from RPC server","hostname":"myserver.domain.net","pid":16150}
0|index    | Error: Callback function "bound _call" timed out.
0|index    |     at Timeout.timeoutCallback [as _onTimeout] (/var/www/scality/node_modules/arsenal/node_modules/async/dist/async.js:4724:21)
0|index    |     at ontimeout (timers.js:386:11)
0|index    |     at tryOnTimeout (timers.js:250:5)
0|index    |     at Timer.listOnTimeout (timers.js:214:5)
```

### Steps to reproduce the issue

```
git clone
cd S3
npm install
pm2 start index.js
```

### Actual result

S3 server works but drops error. This cause PM2 to restart process.

### Expected result

No timeout error.

### Additional information: (Node.js version, Docker version, etc)

```
node v6.11.5
npm v3.10.10
os : Gentoo Linux
```

**Comment by gallart** [comment]
Actually, it looks like I need to start the 3 JS with PM2 :

`pm2 start index.js mdserver.js dataserver.js`

Is that correct?

Thanks,

Gaëtan

**Comment by nicolas2bert** [comment]
Correct, you need to start both data and metadata servers.
