### ISSUE TITLE
Multiple EndPoints On the Same Container

### ISSUE THREAD

**Issue by rainmanh** [scality/S3#1109]
Hi,

I have been having a look into your documentation but I am not sure whether is possible to setup multiple endpoints for the container?

Is that possible? 
If that's possible, where is the right piece of documentation please? As I am failing to find it.

Many thanks

**Comment by LaureVergeron** [comment]
Hello @rainmanh ,
I think what you're looking for is this: http://s3-server.readthedocs.io/en/latest/USING_PUBLIC_CLOUDS/ ; in the locationConfig.json file, you can create new locations, and specify endpoints for these locations.
Let me know if that helps?
Cheers,
Laure
