### ISSUE TITLE
How to create a new account in Cloud Server?

### ISSUE THREAD

**Issue by raxper** [scality/S3#1131]
I am new using your server and wish to implement a client of your own, however, to perform tests necessary to create another user account.

How can I create this account on the server?

I require that this account be able to manage buckets, just as the account that comes by default does.

Thank you very much for your attention.
I am at the expense of your response. Alexis

**Comment by LaureVergeron** [comment]
Hi @raxper ,

What you want to do is effectively edit the [authdata.json](https://github.com/scality/S3/blob/master/conf/authdata.json) file, to add a new Account. Assuming you want to keep the first two existing accounts, it should be of that form:

``` json
{
    "accounts": [{
        "name": "Bart",
        "email": "sampleaccount1@sampling.com",
        "arn": "arn:aws:iam::123456789012:root",
        "canonicalID": "79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be",
        "shortid": "123456789012",
        "keys": [{
            "access": "accessKey1",
            "secret": "verySecretKey1"
        }]
    }, {
        "name": "Lisa",
        "email": "sampleaccount2@sampling.com",
        "arn": "arn:aws:iam::123456789013:root",
        "canonicalID": "79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2bf",
        "shortid": "123456789013",
        "keys": [{
            "access": "accessKey2",
            "secret": "verySecretKey2"
        }]
    }, {
        "name": "newUser",
        "email": "new.user@urdomain.com",
        "arn": "arn:aws:iam::123456789014:root",
        "canonicalID": "79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2bg",
        "shortid": "123456789014",
        "keys": [{
            "access": "newAccessKeyOfYourChoice",
            "secret": "newSecretKeyOfYourChoice"
        }]
    }]
}
```

Assuming you run your service as a daemon, you'll need to restart the container to reload the config file (see [this thread](https://github.com/moby/moby/issues/15793#issuecomment-135411504) for more info) .

Please let me know if that answered your question.
