### ISSUE TITLE
2GB file fails to download via Cybeduck because of ECONNRESET error

### ISSUE THREAD

**Issue by ipeychev** [scality/S3#1177]
Hello,

There is an issue which is a bit odd - 2GB file fails to download via Cybeduck because of ECONNRESET error *after some time*, for example on the next day after uploading.

Here is what happens:
1. Upload a relatively big file (2GB)
2. Download it immediately with Cyberduck - it wirks fine
3. If you try to download the file on the second day again with Cyberduck, it shows error:
<img width="630" alt="screen shot 2018-03-21 at 06 04 19" src="https://user-images.githubusercontent.com/78014/37695502-1f8812fa-2cd0-11e8-9915-5bc186bd46e0.png">

I configured the S3 server to produce the most detailed log level and here are the [logs](https://github.com/scality/S3/files/1832121/log.zip). Here is a part of them:

```
storage[ea88fa34] {"name":"S3","bucketName":"storage","objectKey":"myfiles/bigfile/big-random-file","bytesReceived":0,"bodyLength":0,"implName":"file","key":"ab69f046b124cb940d14eb3fa38f9561cdadc5a3","method":"get","time":1521608643672,"req_id":"8cc687ce474389864f25","level":"debug","message":"sending get to datastore","hostname":"ea88fa347352","pid":153}
storage[ea88fa34] {"name":"DataFileRESTClient","hostname":"ea88fa347352","port":9991,"path":"/DataFile/ab69f046b124cb940d14eb3fa38f9561cdadc5a3","headers":{"X-Scal-Request-Uids":"8cc687ce474389864f25"},"time":1521608643672,"req_id":"8cc687ce474389864f25:1a35cd8ff749acdf66bd","level":"debug","message":"about to send GET request","pid":153}
storage[ea88fa34] {"name":"DataFileRESTServer","method":"GET","url":"/DataFile/ab69f046b124cb940d14eb3fa38f9561cdadc5a3","time":1521608643673,"req_id":"8cc687ce474389864f25:517697ec9c4cbf47bb33","level":"debug","message":"request received","hostname":"ea88fa347352","pid":95}
storage[ea88fa34] {"name":"DataFileRESTServer","key":"ab69f046b124cb940d14eb3fa38f9561cdadc5a3","filePath":"/usr/src/app/lib/../localData/38/ab69f046b124cb940d14eb3fa38f9561cdadc5a3","time":1521608643673,"req_id":"8cc687ce474389864f25:517697ec9c4cbf47bb33","level":"debug","message":"stat file","hostname":"ea88fa347352","pid":95}
storage[ea88fa34] {"name":"DataFileRESTServer","method":"get","key":"ab69f046b124cb940d14eb3fa38f9561cdadc5a3","filePath":"/usr/src/app/lib/../localData/38/ab69f046b124cb940d14eb3fa38f9561cdadc5a3","time":1521608643675,"req_id":"8cc687ce474389864f25:517697ec9c4cbf47bb33","level":"debug","message":"opening readStream to get data","hostname":"ea88fa347352","pid":95}
storage[ea88fa34] {"name":"DataFileRESTServer","key":"ab69f046b124cb940d14eb3fa38f9561cdadc5a3","time":1521608643686,"req_id":"8cc687ce474389864f25:517697ec9c4cbf47bb33","level":"debug","message":"sending back 200/206 response with contents","hostname":"ea88fa347352","pid":95}
storage[ea88fa34] {"name":"S3","time":1521608644301,"error":{"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"},"level":"info","message":"request rejected","hostname":"ea88fa347352","pid":153}
```

What is odd is that if I try to download the file again and again, the first 3-4 times server throws ECONNRESET, and after that it starts to work fine.

Here is some more information: Cyberduck is with default configuration - multiple connections (2) when downloading. In front of S3 there is HAProxy. S3 is serving the files via HTTPS.

Thanks,

**Comment by rahulreddy** [comment]
Hi @ipeychev 
Based on the logs it looks like somehow the source data stream is getting disconnected right around the time when the data is being piped out to the client. Is it possible that the client you are using initiated a timeout, thereby retrying the request again? The ECONNRESET happens usually when the socket is destroyed because the data stream has an error.

**Comment by rahulreddy** [comment]
Also, which version of S3 are you using? Is it master? And what is the nodejs version on the machine that this running S3?

**Comment by ipeychev** [comment]
Hey @rahulreddy,

> Is it possible that the client you are using initiated a timeout, thereby retrying the request again?

I don't know for sure if the client (Cyberduck) initiated a timeout. What I saw was:
1. Cyberduck downloaded successfully several small files (1-3KB).
2. When downloading the big file, it stopped after maybe 300MB, then tried again several times until it gave up.

I installed S3 from the official Docker image (6018536a, latest) so the version is those there. The version of Node seems to be 6.x.

**Comment by rahulreddy** [comment]
@ipeychev 
It's possible that you are hitting a timeout on Cyberduck. You can try awscli to see if you are running into the same issue and isolate the problem.
About the Docker image, I am waiting for a few fixes to be ported. Once it's stable I will push up a new image.

**Comment by ipeychev** [comment]
Okay, @rahulreddy, I will try with aws cli and let's see.
Thanks!

**Comment by ipeychev** [comment]
For the record, I checked and with aws cli the file was downloaded successfullty, while Cyberduck failed in the same way. This was with the default settings of Cyberduck - multiple connections (2).
So, we may consider this issue is not with the server and I'm closing the issue.
Thanks!

**Comment by LaureVergeron** [comment]
Thanks for letting us know, @ipeychev
