### ISSUE TITLE
Deployment in Kubernetes.

### ISSUE THREAD

**Issue by GajananMore** [scality/S3#1226]
# How can deploy scality s3 in kubernetes?

## Bug report information

I found docker image in repo of scality s3. can someone guide me, how would I use scality s3 in kubernetes instead of docker swarn or how can I provision seperate pod for metadata,data and scality server?
 

### Description

I am trying to use kubernetes for deploying scality s3. where I was also trying to mount metadata and data on persisted volume.

**Comment by LaureVergeron** [comment]
Hello @GajananMore ,

Please use our [forum](https://forum.zenko.io), as this is where our community is most present to help you with such questions You may sign in using GitHub OAuth, no need to create a specific account :) .
Cheers!

Laure
