### ISSUE TITLE
SocketError with Ruby on Rails

### ISSUE THREAD

**Issue by swaps19** [scality/S3#135]
I am using `RoR` to integrate the `scality s3 server`. I followed instructions given on a master page and started the server using `npm start` (also tried with `npm run mem_backend`). But I am not able to connect to the `s3` from my rails app. It is just giving me the `SocketError: Failed to open TCP connection to my-bucket.127.0.0.1:8000 (getaddrinfo: nodename nor servname provided, or not known)`.
I am not sure what am I missing?
Also is it compulsory to use `scality s3` with `docker` as specified on the website?

**Comment by nicolas2bert** [comment]
Hey @swaps19 ,
- You should consider using path-style access (`http://127.0.0.1:8000/my-bucket`) instead of `http://my-bucket.127.0.0.1:8000 `.
- No, it is not compulsory to use `scality s3` with `docker`, you can run it with `github`.

**Comment by swaps19** [comment]
@nicolas2bert thanks for the suggestion but I am creating a bucket! So how can I pass a `bucket-name` directly in a URL?

I am using following code to connect with S3-

`s3 = AWS::S3.new(s3_endpoint: '127.0.0.1:8000',access_key_id: 'accessKey1', secret_access_key: 'verySerectKey1'`

this line gives me the object of `AWS::S3`
and following code is being used to create a bucket-

`bucket = s3.buckets.create('my-bucket')`

What am I missing here?

**Comment by rahulreddy** [comment]
@swaps19 Give this a shot 
```ruby
s3 = AWS::S3.new(s3_endpoint: 'http://127.0.0.1:8000',access_key_id: 'accessKey1', secret_access_key: 'verySerectKey1', force_path_style: true)
```
This should force the client to use path-style requests.

**Comment by swaps19** [comment]
@rahulreddy still the same error just the URL it is showing is changed!

before-
`SocketError: Failed to open TCP connection to bucket-name.127.0.0.1:8000 (getaddrinfo: nodename nor servname provided, or not known)`

after-
`SocketError: Failed to open TCP connection to my-bucket.http:443 (getaddrinfo: nodename nor servname provided, or not known)`

**Comment by rahulreddy** [comment]
Ok, let's try to see if you can connect to the server without the sdk. After launching the server,
try using curl like `curl http://127.0.0.1:8000` and see if you get an `AccessDenied` error from the server. This would at least establish that the port is reachable.

Next you can try this. I could be wrong but from the initialization **AWS::S3.new** it looks like it is v1 version of AWS sdk, so the options seem to be different, try
```ruby
s3 = AWS::S3.new(s3_endpoint: 'http://127.0.0.1:8000',access_key_id: 'accessKey1', secret_access_key: 'verySerectKey1', s3_force_path_style: true, use_ssl: false)
```
Link to the ruby gem documentation [here](http://www.rubydoc.info/gems/aws-sdk-v1/1.66.0/AWS#config-class_method)

**Comment by swaps19** [comment]
- `curl http://127.0.0.1:8000` is getting an `AccessDenied` page as expected, I am also getting logs on a server for the `curl` request.

- The options we are using for connection seems to be fine as I also checked with the documentation. We are using the `aws-v1` only. Could this be the problem with `scality s3`?

**Comment by rahulreddy** [comment]
I noticed that there is a typo in the secret key. It should corrected to verySe**c**rectKey1 (notice the missing c). But this does not explain why your client is unable to reach the server, I am out of options here. Can you give this a shot with v2 instead?

**Comment by swaps19** [comment]
@rahulreddy yes! you were right. secret key value was a typo but it didn't work even after passing a correct secret key.

I made it work by removing the `http://` in `s3_endpoint`.
so the new code would be like `s3 = AWS::S3.new(s3_endpoint: '127.0.0.1:8000',access_key_id: 'accessKey1', secret_access_key: 'verySecretKey1', s3_force_path_style: true, use_ssl: false)`

thanks for the help... :)
