### ISSUE TITLE
Transaction request logs

### ISSUE THREAD

**Issue by Mariosworld11** [scality/S3#145]
I am getting HTTP/1.1 400 Bad Request and wanted to track down the transaction request in the server logs. Where do I find these logs?

**Comment by nicolas2bert** [comment]
Hey @Mariosworld11 ,

In order to get an instance’s log path:
`$ docker inspect --format='{{.LogPath}}' $INSTANCE_ID`

**Comment by Mariosworld11** [comment]
Seems like I am missing an argument, Here is what I see:
docker@default:~$ docker inspect --format='{{.LogPath}}' $INSTANCE_ID
docker: "inspect" requires a minimum of 1 argument.


More info about my issue:
I am currently using "Virtual Hosted Style" for Endpoint access to my Scality s3server. But I am seeing in my logs:
14:52:54.024 [7736.2440] <2> pitbull: == Info: Connected to s3server.xxxx.com (192.168.99.100) port 32768 (#0)
14:52:54.024 [7736.2440] <2> pitbull: => Send header, 0000000207 bytes (0x000000cf) 0000: GET / HTTP/1.1 0010: Host: s3server.xxxx.com:32768 0032: Accept: */* 003f: Date:Mon, 15 Aug 2016 21:52:53 GMT 0063: Authorization: AWS accessKey1:pz/Qz34WZPx4Ow4jgS/u3V+fhuE= 009f: user-agent:APN/1.0 xxxxx/1.0 xxxxx/7.7 00cd:
14:52:54.024 [7736.2440] <4> pitbull: CurlHttpClient: After curl_multi_perform: aReadyNess = 1, mStillRunning = 1
14:52:54.063 [7736.2440] <2> pitbull: <= Recv header, 0000000026 bytes (0x0000001a) 0000: HTTP/1.1 400 Bad Request
14:52:54.063 [7736.2440] <2> pitbull: <= Recv header, 0000000018 bytes (0x00000012) 0000: server: AmazonS3

14:52:54.064 [7736.2440] <8> pitbull: AmzResiliency: XML String <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidURI</Code><Message>Couldn't parse the specified URI.</Message><Resource></Resource><RequestId>042a51d008851da8b088</RequestId></Error>
14:52:54.064 [7736.2440] <8> pitbull: AmzResiliency: XML errorcode InvalidURI

I tried to also use "Path Style" for the Endpoint access style but did not work either.

Please let me know what logs I can look at to trace this issue.

Thanks.

**Comment by nicolas2bert** [comment]
Hey @Mariosworld11, 
I think you forgot to replace the $INSTANCE_ID by your S3server instance/containder ID.

`$ docker inspect --format='{{.LogPath}}' $INSTANCE_ID` 
where $INSTANCE_ID is the id of your S3server instance/container id.

You can get your instance id doing a : `docker ps`

**Comment by Mariosworld11** [comment]
Thanks for the information. I am a new user to Docker and Scality.

I looked at the container logs but does not seem useful:
{"log":"{\"name\":\"S3\",\"clientIP\":\"::ffff:192.168.99.1\",\"clientPort\":51749,\"httpMethod\":\"GET\",\"httpURL\":\"/\",\"time\":1471359025156,\"req_id\":\"37b3e42261ee670749f3\",\"level\":\"info\",\"message\":\"received request\",\"hostname\":\"69e28240cdf4\",\"pid\":34}\r\n","stream":"stdout","time":"2016-08-16T14:50:25.157818497Z"}
{"log":"{\"name\":\"S3\",\"clientIP\":\"::ffff:192.168.99.1\",\"clientPort\":51749,\"httpMethod\":\"GET\",\"httpURL\":\"/\",\"httpCode\":400,\"time\":1471359025194,\"req_id\":\"37b3e42261ee670749f3\",\"elapsed_ms\":40.539499,\"level\":\"info\",\"message\":\"responded with error XML\",\"hostname\":\"69e28240cdf4\",\"pid\":34}\r\n","stream":"stdout","time":"2016-08-16T14:50:25.195635059Z"}


I posted some information about my issue regarding http error 400 bad request. Have you seen this before or InvalidURI? Please let me know if there are other logs I should look at.

Thanks

**Comment by nicolas2bert** [comment]
Hey @Mariosworld11 
If you specified a host name (e.g. s3server.xxxx.com)
Add a new region to your `config.json` :

```
"regions": {

     ...

     "localregion": ["localhost"],
     "specifiedregion": ["s3server.xxxx.com"]
},
```

Yes, you can provide your own config.json using Docker volume:
`docker run -v $(pwd)/config.json:/usr/src/app/config.json --net=host -d scality/s3server`

**Comment by Mariosworld11** [comment]
I added your recommendation to the following file under the host options:
C:\Users\Administrator\.docker\machine\machines\default\config.json

I restarted my s3server using Kinematic, but I am still getting the same errors.
14:33:25.332 [3516.7936] <2> pitbull: <= Recv header, 0000000026 bytes (0x0000001a) 0000: HTTP/1.1 400 Bad Request
14:33:25.333 [3516.7936] <8> pitbull: AmzResiliency: XML String <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidURI</Code><Message>Couldn't parse the specified URI.</Message><Resource></Resource><RequestId>6698a63504ff0d4c8008</RequestId></Error>
14:33:25.333 [3516.7936] <8> pitbull: AmzResiliency: XML errorcode InvalidURI

In the Docker machine VBox.log I see the following:
00:00:44.441342 VMMDev: Guest Log: 00:00:00.018192 main     5.0.24 r108355 started. Verbose level = 0
00:00:44.448066 VMMDev: Guest Log: 00:00:00.024979 vminfo   rtldrNativeLoad: dlopen('libdbus-1.so.3', RTLD_NOW | RTLD_LOCAL) failed: libdbus-1.so.3: cannot open shared object file: No such file or directory
00:00:44.448150 VMMDev: Guest Log: 00:00:00.025081 vminfo   Error: Unable to connect to system D-Bus (1/3): D-Bus not installed
00:00:45.336877 NAT: IPv6 not supported
00:00:49.453187 VMMDev: Guest Log: 00:00:05.030949 vminfo   Error: Unable to connect to system D-Bus (2/3): D-Bus not installed
00:00:54.454939 VMMDev: Guest Log: 00:00:10.032730 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed

VirtualBox logs (VBoxSVC.log) shows the following:
16:49:26.856309          ERROR [COM]: aRC=VBOX_E_OBJECT_NOT_FOUND (0x80bb0001) aIID={f30138d4-e5ea-4b3a-8858-a059de4c93fd} aComponent={SessionMachine} aText={No storage device attached to device slot 0 on port 29 of controller 'SATA'}, preserve=false aResultDetail=0
16:49:26.955061          ERROR [COM]: aRC=E_FAIL (0x80004005) aIID={f30138d4-e5ea-4b3a-8858-a059de4c93fd} aComponent={SessionMachine} aText={This machine does not have any snapshots}, preserve=false aResultDetail=0

Question:
-Do you know how to turn up logging verbosity on Docker? I will research this.
-Also I will look into disabling IPv6, according to my logs it is connecting using IPv6.
14:33:24.255 [3516.7936] <2> pitbull: CSSCCLIENT:   == Info:   Trying fe80::50d8:bb06:dd1d:f7a9...
14:33:24.265 [3516.7936] <2> pitbull: CSSCCLIENT:   == Info: Connected to pitbull (fe80::50d8:bb06:dd1d:f7a9) port 5637 (#0)

Just so you know, I am able to use Cloudberry to connect to the VM, create a bucket, and transfer a file. Please let me know if you have feedback on what you see.

Another question that I have is if you support the underscore _ in the header?
pitbull: => Send header, 0000000215 bytes (0x000000d7) 0000: GET //s3serverdemo/ HTTP/1.1 001e: Host: 192.168.99.100:32768 003a: Accept: */* 0047: Date:Thu, 11 Aug 2016 19:44:38 GMT 006b: Authorization: AWS 

"<HttpHeader Value="APN/1.0 xxxxx/1.0 xxxxx/#XXX_MAJOR#.#XXX_MINOR#" PossibleValues="APN/1.0 xxxxx/1.0 xxxxx/#XXX_MAJOR#.#XXX_MINOR#" Level="all" Key="User-Agent" Fixed="true" Description="Cloud storage consumer identifier"/>"

Thanks for your help.

-mario

**Comment by nicolas2bert** [comment]
Hey Mario, 
Are you sure you mounted the right  [config.log](https://github.com/scality/S3/blob/master/config.json) ?
What do you mean by `underscore _ in the header` ?
In order to see more log, you can change your `"log"` section inside your [config.log](https://github.com/scality/S3/blob/master/config.json)
```
"log": {
   "logLevel": "debug",
  "dumpLevel": "error"
}
```
