### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by rsjones** [scality/S3#155]
I compiled on windows 8.1 successfully with python 2.7 and visual studio community edition but got an error when running npm start. Attached the npm-debug file.

[npm-debug.txt](https://github.com/scality/S3/files/428060/npm-debug.txt)

**Comment by nicolas2bert** [comment]
Hey @rsjones , 
```
2 info using npm@3.3.4
3 info using node@v4.5.0
```
Can you downgrade your npm from  3 to 2.7 or greater?

ie: ` 2.7 <= npm < 3 `

And then, `npm install` and `npm start`

Nicolas

**Comment by rsjones** [comment]
Thanks @nicolas2bert for the reply, I downgraded to node 4.2 and installed npm 2.7.6 in my global package install. Afterward the error appears identical. I made sure that I deleted my node_modules directory in my project before running `npm install` and `npm start`.

I'd also make the suggestion that the python and .Net SDK (probably VisualStudio Community or Express edition for Win 8+ support) be added a dependencies for Windows. I was surprised to find the project required those based on the current readme.

Thanks for the help

[npm-debug.txt](https://github.com/scality/S3/files/428486/npm-debug.txt)

**Comment by nicolas2bert** [comment]
Hey @rsjones , we are figuring out why you are getting these errors. 
You should try using our Docker image https://hub.docker.com/r/scality/s3server/ so, you won't have to deal with these windows configurations.

**Comment by rsjones** [comment]
Thanks @nicolas2bert, I actually have the docker image running, but for reasons I won't bore you with, I'm trying to run it disconnected from the internet and haven't had luck getting docker to install there. So getting this to run outside of docker would help. It also appears that there might be a min requirement of RHEL 7, b/c I wasn't able to successfully get it to build on RHEL 6. I haven't had time to spin up a RHEL 7 instance yet to yet though.

**Comment by nicolas2bert** [comment]
I see, do you get any error during the `npm install` ?

**Comment by rsjones** [comment]
No errors. I reran install with verbose on so you can see the results.
[install.txt](https://github.com/scality/S3/files/437589/install.txt)

**Comment by nicolas2bert** [comment]
Hey @rsjones , 
Do you have any updates?

**Comment by rsjones** [comment]
Nope I was hoping y'all were looking at this. I can't figure out why it's not building on windows, we're you able to build it?

**Comment by NicolasT** [comment]
Could it be that executing `node init.js && node index.js`, which is the `start` entry-point listed at https://github.com/scality/S3/blob/d3ba43b87ce07a640ade2413f5f915e178a73dff/package.json#L66 isn't really a valid call-out on Windows, hence the process error in the attached `npm-debug.txt`?

Disclaimer: not really a Windows or Node-on-Windows expert...

**Comment by nicolas2bert** [comment]
@NicolasT , we are working on it. I will keep you updated.

**Comment by rahulreddy** [comment]
I identified two issues

1. init.js throws an assertion if the directories for localData already exist
```
AssertionError: Error creating data files Error: EEXIST: file already exists, mkdir 'C:\Users\foo\S3\localData\0'
    at C:\Users\foo\S3\init.js:81:13
    at C:\Users\foo\S3\node_modules\async\lib\async.js:52:16
    at C:\Users\foo\S3\node_modules\async\lib\async.js:267:21
    at C:\Users\foo\S3\node_modules\async\lib\async.js:44:16
    at C:\Users\foo\S3\init.js:75:20
    at FSReqWrap.oncomplete (fs.js:82:15)
```
as we are not using the windows error number -4075 (File already exists error) to skip the error. We should opt for using error code `EEXIST` instead of numbers for system error detection as they are consistent across the systems.

2. index.js - uses a list of files for babel to ignore, i.e, not to transpile. This is not working on Windows for reasons I don't know yet. I am working on a solution to statically transpile utapi module so that we don't have to provide this list.

I will be making some PRs to fix these issues.

**Comment by rahulreddy** [comment]
I have verified that PRs #214  and #215 fix the issues. `npm install` and `npm start` should on Windows now.
