### ISSUE TITLE
problems connecting

### ISSUE THREAD

**Issue by moonwalk123** [scality/S3#177]
I have launched an instance of your s3 using Docker and can successfully talk to it using cyberduck using an IP address

My software has a requirement to use FQDNs for all addresses, and when I try to connect I get the following error: "Couldn't parse the specified URI.".

How do I configure it to use hostnames?

**Comment by nicolas2bert** [comment]
If you specified a host name (e.g. `myhostname.com`)
Add a new region to your config.json :

```
"regions": {

     ...

     "localregion": ["localhost"],
     "specifiedregion": ["myhostname.com"]
},
```

You can provide your own config.json using Docker volume:

`docker run -v $(pwd)/config.json:/usr/src/app/config.json --net=host -d scality/s3server`

**Comment by nicolas2bert** [comment]
Hey @moonwalk123, does it help?

Let me know,

Nicolas

**Comment by moonwalk123** [comment]
thanks, that worked

Just trying to get SSL set up at the moment, is their a configuration option I need to turn on for that to work?

**Comment by nicolas2bert** [comment]
Yes @moonwalk123 ,

Add the following section to your `config.log`

```
"certFilePaths": {
    "key": "YOUR/PRIVATE/KEY/PATH",
    "cert": "YOUR/PUBLIC/KEY/PATH", 
}
```
If you are using self-signed certification, on your client side, you will have to either provide a certificate authority or disable the certificate checking.

**Comment by moonwalk123** [comment]
Thanks for your help, got everything up and running
