### ISSUE TITLE
Interoperability Failure Error

### ISSUE THREAD

**Issue by snoopj123** [scality/S3#195]
Using latest Docker container version, whenever I connect to the store and try to create a new folder, I receive the following error:  **Interoperability failure** - Bucket name is not DNS compatible.  Please contact your web hosting service provider for assistance.

This is using Cyberduck and I've had this happen with both Docker running the following combinations:

- Docker on Mac/Cyberduck on Mac
- Docker on Ubuntu 16.04.1/Cyberduck on Windows 10

Attached is the error message I've received.  Don't know if I'm missing a configuration in Cyberduck or something on the container side.

![screen shot 2016-09-06 at 10 13 30 am](https://cloud.githubusercontent.com/assets/11169922/18291995/981fd552-7450-11e6-984e-3aa7d5206f04.png)

**Comment by nicolas2bert** [comment]
Can you check or send me your Cyberduck configuration?
Nickname : WhateverYouWant

URL: http://accessKey1@`MACHINE_IP`:`PORT`/
where `MACHINE_IP` is the IP address of your docker machine (your Ubuntu VM). 
You can do `docker-machine ip` to get this IP
`PORT` is the port listed, you probably configured it on Kitematic or when you `docker run -d --name s3server -p 8000:8000 scality/s3server `

Server: `MACHINE_IP`
Access Key ID: accessKey1

I attached my configuration, if that can help. 
I am using Docker for Mac that runs as a "native" Mac application.
That is why my `MACHINE_IP` is 127.0.0.1.
![screen shot 2016-09-06 at 5 53 51 pm](https://cloud.githubusercontent.com/assets/7453636/18296726/8f5f2c32-7460-11e6-9507-b7668ea01d6b.png)

**Comment by snoopj123** [comment]
For my setup at home (the Ubuntu VM and Windows 10), this is what I'm using:

Docker container is just as you stated.  Port 8000 mapped to port 8000 in the container.  IP address of the VM is 192.168.56.128, my Windows machine is 192.168.56.1 (using VMware Workstation and using the isolated internal only network with the Windows 10 machine).

Configuration image below...

![error_image](https://cloud.githubusercontent.com/assets/11169922/18297745/c13fe30a-7478-11e6-8820-6b5d582af332.png)

**Comment by nicolas2bert** [comment]
Your config looks ok.
Can you give me your s3Server logs when connecting to the S3server with Cyberduck?

Thanks,

Nicolas

**Comment by snoopj123** [comment]
Will do.  I'll try to give it a whirl tonight.

**Comment by snoopj123** [comment]
Searching around the container.  Any specific location where the log files going?  I feel like I've been all over the file system in the container and can't seem to locate the log file location.  I know, silly question, but my eyes must be going.

**Comment by nicolas2bert** [comment]
Yes,so if you do` docker inspect CONTAINER_ID  | grep log`, that should return the log path.

**Comment by snoopj123** [comment]
[output.txt](https://github.com/scality/S3/files/463158/output.txt)

Logging doesn't look like much.  The last 6 lines were the connection to the host and there didn't appear to be anything logged, at least server side, when I got the error message in Cyberduck.

**Comment by nicolas2bert** [comment]
Hey @snoopj123 ,

There may be something wrong with the name of the bucket you are trying to create.

Did you follow the [AWS Bucket Restriction](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) ?

```
Bucket names must be at least 3 and no more than 63 characters long.
Bucket names must be a series of one or more labels. Adjacent labels are separated by a single period (.). Bucket names can contain lowercase letters, numbers, and hyphens. Each label must start and end with a lowercase letter or a number.
Bucket names must not be formatted as an IP address (e.g., 192.168.5.4).
When using virtual hosted–style buckets with SSL, the SSL wildcard certificate only matches buckets that do not contain periods. To work around this, use HTTP or write your own certificate verification logic. We recommend that you do not use periods (".") in bucket names.
```

**Comment by snoopj123** [comment]
Just realized that.  We can close this with a root cause of a new guy being an idiot (I was using a capital letter in the name of the bucket and it appears it doesn't like that.  "Test" doesn't work, "test" does work.   /facepalm

**Comment by nicolas2bert** [comment]
Totally fine ! Enjoy your S3server now !
