### ISSUE TITLE
Getting a fatal error after "docker start" command

### ISSUE THREAD

**Issue by esignoretti** [scality/S3#201]
Hi,
I'm testing the S3server on a Digital Ocean VM (Ubuntu 14.04 - Docker 1.11.02).

I followed the istrucntions on the web site:
Docker pull...
Docker run...
Docker start...

the S3server starts but just after a few seconds it exits and this is what I get from the log: 

> s3@1.1.0 start /usr/src/app
> node init.js && node index.js

{"name":"S3","level":"info","message":"FS_DIRSYNC_FL set","hostname":"83acbde5c8e1","pid":17}
{"name":"S3","level":"info","message":"FS_DIRSYNC_FL set","hostname":"83acbde5c8e1","pid":17}
{"name":"S3","level":"info","message":"Init complete.  Go forth and store data.","hostname":"83acbde5c8e1","pid":17}
{"name":"S3","level":"warn","message":"scality kms selected but unavailable, using file backend","hostname":"83acbde5c8e1","pid":27}
{"name":"S3","level":"info","message":"starting metadata file backend server","hostname":"83acbde5c8e1","pid":27}
{"name":"S3","workerId":7,"level":"error","message":"worker disconnected. making sure exits","hostname":"83acbde5c8e1","pid":27}
{"name":"S3","workerId":7,"level":"error","message":"worker exited.","hostname":"83acbde5c8e1","pid":27}
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at exports.fork (child_process.js:54:10)
    at createWorkerProcess (cluster.js:307:12)
    at EventEmitter.cluster.setupMaster.cluster.fork.env [as fork] (cluster.js:341:27)
    at [object Object]._repeat (/usr/src/app/lib/server.js:114:47)
    at [object Object].wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

npm info s3@1.1.0 Failed to exec start script
npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! s3@1.1.0 start: `node init.js && node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@1.1.0 start script 'node init.js && node index.js'.
npm ERR! This is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node init.js && node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

what did I do wrong?
thank you very much.

**Comment by esignoretti** [comment]
never mind. I was using a very small VM... :/

**Comment by GiorgioRegni** [comment]
Thanks for resolving the issue on your own @esignoretti !
How's your testing going?

**Comment by esignoretti** [comment]
Ciao Giorgio,
the testing is going very well. it was sufficient to add a swap file to the linux instance. 
now I have an object store that costs me $5/month :D
tomorrow I’ll look for Wordpress plug-ins to see if I can store media files on it. 

I wrote a blog about it: http://www.juku.it/en/s3-object-storage-on-digital-ocean-with-scalitys-s3server/ <http://www.juku.it/en/s3-object-storage-on-digital-ocean-with-scalitys-s3server/>

Best,
Enrico
