### ISSUE TITLE
Is there a guide for connecting with cli's and sdk's

### ISSUE THREAD

**Issue by ryanwilliamquinn** [scality/S3#209]
I'm having trouble connecting to my docker instance with s3cmd (v1.6.1), and the aws node sdk. I was able to connect via cyberduck. Is there any configuration guide for these other tools?  Thanks.

**Comment by nicolas2bert** [comment]
Hey @ryanwilliamquinn 

If you do: `s3cmd --configure`

```
Access Key: accessKey1 
Secret Key: verySecretKey1 
Default Region: us-west-1
Encryption password: 
Path to GPG program: None
Use HTTPS protocol: False
HTTP Proxy server name: MACHINE_IP
HTTP Proxy server port: PORT
```

where:
- `MACHINE_IP` is the IP address of your docker machine (your Ubuntu VM). 
You can do docker-machine ip to get this IP.

- `PORT` you probably configured it on Kitematic or if you did: `docker run -d --name s3server -p 8000:8000 scality/s3server
![screen shot 2016-09-14 at 12 59 19 pm](https://cloud.githubusercontent.com/assets/7453636/18530199/374df5f2-7a85-11e6-9a5e-41d4b9f9829d.png)
`

**Comment by nicolas2bert** [comment]
@ryanwilliamquinn, did you manage to connect?

**Comment by ryanwilliamquinn** [comment]
Thanks for your help with this @nicolas2bert.  I had overlooked disabling HTTPS, and that was breaking things. I didn't have to use the proxy, my configure prompts were slightly different than the ones you show. They included an endpoint field. Maybe we are on different versions of s3cmd.
