### ISSUE TITLE
CA should be optional for client libs

### ISSUE THREAD

**Issue by RachedBenMustapha** [scality/S3#236]
In case a certificate is used that is signed by a known authority (present in the system bundles) we should allow leaving the "ca" option empty, otherwise client libs such as vaultclient and bucketclient get confused an fail with errors such as:

```
{"name":"S3","accessKey":"4W63JJQ5VRHHU0JE718I","errCode":{"code":"UNABLE_TO_GET_ISSUER_CERT"},"time":1475091247515,"req_id":"ebd74164b1da19a96d8c","level":"trace","message":"sending error xml response","hostname":"demo.scalitydemo.com","pid":64}
{"name":"S3","accessKey":"4W63JJQ5VRHHU0JE718I","errorMessage":{"code":"ECONNRESET"},"time":1475091247661,"req_id":"ebd74164b1da19a96d8c","level":"error","message":"received error message from vault","hostname":"demo.scalitydemo.com","pid":64}
```

**Comment by dhekimian** [comment]
@RachedBenMustapha Any update on the status of this issue?

**Comment by RachedBenMustapha** [comment]
@dhekimian after looking closer it seems there's no issue on the S3 server but rather on the deployment side, closing this one.

**Comment by GiorgioRegni** [comment]
So is there another ticket in Federation? @RachedBenMustapha

**Comment by RachedBenMustapha** [comment]
@GiorgioRegni scality/Federation#602
