### ISSUE TITLE
No tag on docker image for scality/s3server

### ISSUE THREAD

**Issue by Tiduster** [scality/S3#241]
Hello !

For the moment we use your docker image in our deployment, mostly because it's easier to upgrade.
But as there isn't any tag on hub.docker.com, we can't know for sure what version we are using, and we can't easily install the same version on several servers.

Do you think you can add some during your next release on docker hub ?

Sorry if this issue is misplaced.

Best regards,

**Comment by nicolas2bert** [comment]
Hey @Tiduster ,
We are discussing about that.
Will come back to you soon.

**Comment by nicolas2bert** [comment]
Hey @Tiduster ,

We started versioning our Docker image using our git commit hashes.
Check it out: https://hub.docker.com/r/scality/s3server/

**Comment by Tiduster** [comment]
Hey @nicolas2bert ,
Thanks for the quick reaction, commit hashes is a good idea, and it solve my issue.

May I ask for a stable tag too ? :-)

And it will be perfect.

Best regards,
