### ISSUE TITLE
SignatureDoesNotMatch using aws (python boto2) cmdline and github.com/aws/aws-sdk-go/aws (go)

### ISSUE THREAD

**Issue by jrwren** [scality/S3#245]
$ aws --profile scality --endpoint-url http://127.0.0.1:8000 s3 ls

A client error (SignatureDoesNotMatch) occurred when calling the ListBuckets operation: The request signature we calculated does not match the signature you provided.

or using simple go example:

panic: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided.
	status code: 403, request id: 991c4abd83a7b23c63f7

**Comment by nicolas2bert** [comment]
Hey @jrwren,

You need to add the AWS credentials: `access_key` and `secret_key` to the configuration.

You can use : `aws configure` command :

```
WS Access Key ID [****************]: accessKey1
AWS Secret Access Key [****************]: verySecretKey1
Default region name [us-east-1]: 
Default output format [json]: 
```

**Comment by jrwren** [comment]
that is exactly what I have.

That is pretty close to what I have and what I have is correct.

If i use a [scality] header, instead of [profile scality] header, I get an error `The config profile (scality) could not be found`

If I set aws_access_key_id to a value that is not accessKey1, I get an error `A client error (InvalidAccessKeyId) occurred when calling the ListBuckets operation: The AWS access key Id you provided does not exist in our records.`

So it seems I have the correct config:

```
[profile scality]
aws_access_key_id = accessKey1
aws_secret_access_key = verySecretKey1
region = localregion
```

and that the error is not related to these config settings.

```
$ aws --profile scality --endpoint-url http://192.168.15.197:8000 s3 ls

A client error (SignatureDoesNotMatch) occurred when calling the ListBuckets operation: The request signature we calculated does not match the signature you provided.
```

**Comment by nicolas2bert** [comment]
That is because you can place your credential in either:

`~/.aws/credentials` (or in `%UserProfile%\.aws/credentials` on Windows).

```
[scality]
aws_access_key_id = accessKey1
aws_secret_access_key = verySecretKey1
```
or

`~/.aws/config` (or in `%UserProfile%\.aws\config` on Windows).

Here, you have to specify **profile** before the profile name.

```
[profile scality]
aws_access_key_id = accessKey1
aws_secret_access_key = verySecretKey1
```

Can you try updating your default config (do not specify any region):

```
[default]
aws_access_key_id = accessKey1
aws_secret_access_key = verySecretKey1
```

You can get more informations about command line interface for amazon web services [here](https://github.com/aws/aws-cli).

**Comment by jrwren** [comment]
That is very interesting.  FTR, I had `[profile scality]` in the config file, but... and this is what caused me problems: I ALSO had a `credentials` file.

Looks like having both files is a problem. Which would be used?

I removed credentials file and `[profile scailty]` still does not work.

I use `[default]` section and it does work.

I can run ` aws  --endpoint-url http://192.168.15.197:8000 s3 ls`  without error, and empty result.

So I try to create a bucket using `mb`

```
$ aws --endpoint-url http://192.168.15.197:8000 s3 mb s3://oh
make_bucket failed: s3://oh/ A client error (InvalidBucketName) occurred when calling the CreateBucket operation: The specified bucket is not valid.
```

A little more trying and it seems there is a minimum length on bucket name.

```
$ aws --endpoint-url http://192.168.15.197:8000 s3 mb s3://testb
make_bucket: s3://testb/
$ aws  --endpoint-url http://192.168.15.197:8000 s3 ls
2016-10-04 17:15:04 testb
```

This looks great. Thanks.
