### ISSUE TITLE
support ipv6

### ISSUE THREAD

**Issue by jrwren** [scality/S3#246]
$ curl "[2601:400:8000:7649:1cd0:444a:f079:c9a1]":8000
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidURI</Code><Message>Couldn't parse the specified URI.</Message><Resource></Resource><RequestId>8d0177d030e898552476</RequestId></Error>

**Comment by nicolas2bert** [comment]
Hey @jrwren,
Thanks for your feedback, supporting ipv6 has not been implemented yet.
However, it's in our Roadmap so you can expect it soon.

**Comment by LaurenSpiegel** [comment]
Fixed by https://github.com/scality/S3/pull/482
