### ISSUE TITLE
[CDMI] Add proper pagination to listing - MaxKeys etc

### ISSUE THREAD

**Issue by vrancurel** [scality/S3#259]
Add proper pagination to S3/CDMI connector

**Comment by vrancurel** [comment]
Use a blob in the marker, use current dewpoint repositioning algorithm.

**Comment by vrancurel** [comment]
Do we need to sort the output ? @LaurenSpiegel @rahulreddy

**Comment by LaurenSpiegel** [comment]
Listing output should be sorted.  How is the listing being accomplished?

**Comment by ttvi** [comment]
The output is naturally sorted based on the keys because of the leveldb backend (if you're mentioning S3 object listing).

**Comment by rahulreddy** [comment]
@ttvi They are talking about the CDMI backend.
And yeah I am hoping that the output is naturally sorted, as sorting on the S3 side would be expensive.

**Comment by vrancurel** [comment]
I think it is sorted by name in Mesa/SOFS no ?

**Comment by jeremyds** [comment]
I don't know yet but it is simple to test.

**Comment by DavidPineauScality** [comment]
@vrancurel @jeremyds Is this issue really relevant in S3 ? Should it not be located in cdmiclient instead ?

**Comment by vrancurel** [comment]
@DavidPineauScality the project has been created on S3, since it is an S3 data + metadata backend.

**Comment by vrancurel** [comment]
Even if it might be problematic for some applications to output entries in a way which not entirely sorted, unless it is easy to do so, I advice not to focus on this for the moment since the pagination is way more important.

**Comment by LaurenSpiegel** [comment]
@jeremyds, can this be closed?
