### ISSUE TITLE
Add end-to-end test, put the Dockerfile into Integration

### ISSUE THREAD

**Issue by vrancurel** [scality/S3#260]
Add simple integration test.

**Comment by vrancurel** [comment]
Use the current bash scripts and put them in Integration.

**Comment by DavidPineauScality** [comment]
Given that it's for @jeremyds , I'm guessing it has to do with the CDMI backend, right ?

**Comment by jeremyds** [comment]
Yes @DavidPineauScality it is related to the S3/CDMI feature.

**Comment by DavidPineauScality** [comment]
@vrancurel @jeremyds Should this issue(task) not be opened in integration instead ?

**Comment by LaurenSpiegel** [comment]
@jeremyds, can this be closed as well?

**Comment by GiorgioRegni** [comment]
So I am guessing this can be closed now?
