### ISSUE TITLE
[test case] GET RANGE with large end end position

### ISSUE THREAD

**Issue by dmgrimal** [scality/S3#270]
customer request:

NOTE: This does not work with RS2 and needs to work with S3. 

Specific test starts by uploading a 2890 byte object.  Then, retrieve object with a RANGE specified.  Each of these should return the last 91 bytes

- range (2800-) 
- range (2800-INTEGER.max)
- range (2800-LONG.max)

With RS2, the LONG.max causes the RS2 connector to return the first 91 bytes of the object, not the last.  This is wrong.

**Comment by bennettbuchanan** [comment]
Thank you for adding this issue.

The byte offset starts at zero, so the ranges given here will return a 90 byte object (e.g., comprised of bytes 2800–2889), not a 91 byte object. See https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35.

With S3, a range of `bytes=2800-` returns the last 90 bytes of a 2890 byte object.
