### ISSUE TITLE
Can you add Cloud Explorer as a recommended client?

### ISSUE THREAD

**Issue by rusher81572** [scality/S3#277]
Hello, I was wondering if you can add Cloud Explorer as a recommended client per this blog post I wrote: https://www.linux-toys.com/?p=945

It is a useful GUI and CLI client with even performance testing. It would be good to showcase this product.

**Comment by nicolas2bert** [comment]
Hey, @rusher81572 , 

It looks like your link is broken.

**Comment by rusher81572** [comment]
Sorry, having server issues. It will be up tonight =(

**Comment by rusher81572** [comment]
@nicolas2bert Blog is up now. =)

**Comment by nicolas2bert** [comment]
Thanks, we are going to have a look,

Let you know :)

**Comment by rusher81572** [comment]
Thank you @nicolas2bert =). I am sure that you will find the performance testing useful.

**Comment by GiorgioRegni** [comment]
@nicolas2bert  is building a list of applications that have been tested with S3 Server and we'll be sure to include cloudexplorer!

**Comment by rusher81572** [comment]
Thank you very much =)

**Comment by nicolas2bert** [comment]
Hey @rusher81572.
I used your cool Cloud Explorer GUI 8.0 (stable), I have been able to connect to my local s3server and list my buckets. I have not managed to see my objects in my bucket though.
When I start running the performance selecting my bucket, it seems that the request never reached my local server. 
PS: You could make a short video explaining how your last stable version works with our s3Server.

Thank you.

**Comment by rusher81572** [comment]
Helllo @nicolas2bert,

Did you add entries to /etc/hosts like the blog posts says?  The bucket name has to be resolvable in /etc/hosts unless you have wildcard DNS setup automatically. This is a typical AWS SDK requirement for S3. 

Example:

192.168.0.x bucket1.mydomain.com mydomain.com

**Comment by nicolas2bert** [comment]
Ok, will look at it. Still a short video that I could add below your name [here ](https://github.com/scality/S3/blob/891c7920f8e8eecc9173a82dc7eba4490cb5d6c3/GETSTARTED.md) can be really useful. 

Thanks

**Comment by rusher81572** [comment]
@nicolas2bert  Here you go: https://www.youtube.com/watch?v=2hhtBtmBSxE

**Comment by nicolas2bert** [comment]
@rusher81572 
Thank you for this clear and useful video. I will add it to the list.

**Comment by nicolas2bert** [comment]
We just merged our **getting started** section:
https://github.com/scality/S3/blob/master/README.md#cloud-explorer
