### ISSUE TITLE
Add a default endpoint in S3server

### ISSUE THREAD

**Issue by jbrusq** [scality/S3#302]
Context : We want to test an external software with our S3server.
Look like the software needs an DNS resolved endpoint, and doesn't support IP.

It would be nice to have a default endpoint configured in s3server , example : s3server.scality.test.

Workaround : 
Copy configuration from docker (/usr/src/app/config.json), modify it and add your enddpoint on the server (/usr/src/app/config_NEW.json)
    "regions": {
        ...
        "s3.scality.test": ["s3.scality.test"],
        "localregion": ["localhost"]

And restart docker with this new configuration file: 
    docker run  --net=host -v /home/scality/config_NEW.json:/usr/src/app/config.json scality/s3server

**Comment by nicolas2bert** [comment]
Hey @jbrusq ,

If you specified an host name (e.g. `s3.scality.test`), you can provide your own config.json using Docker volume.

First, add a new region to your `config.json` that you created locally:

```
"regions": {

     ...

     "localregion": ["localhost"],
     "specifiedregion": ["s3.scality.test"]
},
```

Then run your s3server using Docker Volume:

`docker run -v $(pwd)/config.json:/usr/src/app/config.json --net=host -d scality/s3server`

**Comment by jbrusq** [comment]
Hi @nicolas2bert ,

Look like the solution you described is the same as the one from the ticket ;)
I just say that it would be nice to have a default endpoint  "s3.scality.test", and avoid updaing the configuration...
Jerome

**Comment by pgueant** [comment]
Hello,

Also the region is not return by a "get-bucket-location" request:

$ aws s3api --endpoint http://<endpoint_name>  get-bucket-location --bucket bucket

{

    "LocationConstraint": null

}

Can we fix this ?
Thanks.

**Comment by nicolas2bert** [comment]
We do not have `get-bucket-location` implemented. 
What the use case really is for it? Because we don't have regional deployments anyway.

**Comment by pgueant** [comment]
Hi,

The use case is precisely having Rings deployed on several geographies and being able to query the region from the application. 

Thanks,
Pierre 

> Le 26 oct. 2016 à 19:46, Nicolas HUMBERT <notifications@github.com> a écrit :
> 
> We do not have get-bucket-location implemented. 
> What the use case really is for it? Because we don't have regional deployments anyway.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
 
<https://www.scality.com/backup/?utm_source=signatures&utm_medium=email&utm_campaign=backup2016>

**Comment by nicolas2bert** [comment]
Ok, I got it @pgueant, can you create a separate issue so? 
Thanks.
