### ISSUE TITLE
Snapshot / Backup of localData and localMetadata content

### ISSUE THREAD

**Issue by Tiduster** [scality/S3#311]
Hello !
If we want to use S3Server in production we need a way to backup our data which ensures that everything is consistent (files and leveldb metadata database).

We would love to save our VM regularly (maybe once per hour), if possible without having to cut the service a few seconds to be sure what we are backing up is synced and consistent.

Do you have an idea to do something like that?
Maybe by sending a signal to the docker to flush data on disk?

If we take PostgreSQL as an example, the database has several instructions to perform consistent PITR save (basically a rsync of everything in /var/lib/postgres). Using signal and flags to inform the SGBD it needs to flush the WAL, write everything to disk, etc...

Thanks!

**Comment by GiorgioRegni** [comment]
Hi @Tiduster thanks for your question, very cool to see production usage of S3 Server by the community!

**Comment by GiorgioRegni** [comment]
As a matter of fact all the IO operations we do are synced, for example metadata writes into leveldb as well as files for object content. So doing a snapshot and saving your VM should always result in a consistent state.
So I am not sure, we would need a signal to force flushing data on disk. @vrancurel can you confirm?

**Comment by vrancurel** [comment]
Yes, both objects and buckets are synced at every operation, so this should work when saving your VM !

**Comment by Tiduster** [comment]
Thanks for the answer.
We are doing some tests and will get back to you as soon as possible.

Regards

**Comment by GiorgioRegni** [comment]
OK, keep us updated!
