### ISSUE TITLE
KMS: Generate encryption key each time we try to create a bucket

### ISSUE THREAD

**Issue by alexandre-merle** [scality/S3#314]
Actually, try to create a bucket already existing lead to a fail from kms, because the key already exist. This is done because here https://github.com/scality/S3/blob/master/lib/api/apiUtils/bucket/bucketCreation.js#L159 we try to create in parrallel both bucket and bucket encryption information, and we do not have a check for already existing key. That being said, create the encryption key before know if the bucket exist is not something we should do :) Same for an bucket creation error, we should delete the related key against kms

**Comment by alexandre-merle** [comment]
i think this is the same for transient buckets, we need to manage it also

**Comment by vrancurel** [comment]
Context: user migration
