### ISSUE TITLE
Create rpm and deb packages automatically

### ISSUE THREAD

**Issue by GiorgioRegni** [scality/S3#325]
It will be very useful to have a way to automatically create:
- rpm for centOS6 and CentOS7
- deb for ubuntu server latest LTS

Just like we create docker images for users to quickly install via apt-get or yum.

@dkilcy will be happy for sure!

**Comment by DavidPineauScality** [comment]
I'm guessing we are talking S3Server here, right ? Or are we talking connector ?

**Comment by dkilcy** [comment]
I'm thinking we could start with S3Server, learn some lessons, then move on to the connector.  I'd like this issue to cover the S3Server only.  Thanks.

**Comment by GiorgioRegni** [comment]
@RachedBenMustapha I am talking with ubuntu to get S3Server in the official repo. Can I assign you on doing .deb package?

**Comment by RachedBenMustapha** [comment]
@GiorgioRegni Sure, are we going to include deb packaging in the s3 git repo directly?

**Comment by GiorgioRegni** [comment]
Let's rethink the package strategy altogether, closing this one for now.
