### ISSUE TITLE
GET object not manage errors

### ISSUE THREAD

**Issue by alexandre-merle** [scality/S3#334]
In the GET object, we do not have error coming back from 'ready-set-stream' package, meaning a failure to sproxyd call will result to a 200 http response, this is problematic :).
Its because the stream is ended when an error occured and we have actually no way to manage the error, we need to update 'ready-set-stream' first and manage this case

**Comment by alexandre-merle** [comment]
the behavior is that :

sproxyd online : s3cmd put ~/Downloads/MD.tar.gz  s3://test/testobject -> OK
sproxyd online : s3cmd get s3://test/testobject -> OK
sproxyd offline / error : s3cmd get s3://test/testobject -> OK but no data

the code flow :

here we do a call to responseStreamData https://github.com/scality/S3/blob/master/lib/routes/routeGET.js#L71
this call will send back the data as a stream, but here https://github.com/scality/ReadySetStream/blob/master/index.js#L29 , if sproxyd send back an error, the stream is just ended while client will receive 200 OK for the request

This behavior lead to the client to wait data until the timeout

**Comment by rahulreddy** [comment]
Ideally, nodejs is supposed to handle this error as we are "uncharted waters" when we send headers, start streaming the data and error occurs during streaming. One of the options I found so far is destroying the socket by using `req.destroy()`. We can explore other options as well, of course.

**Comment by alexandre-merle** [comment]
@rahulreddy response.connection.destroy work well :) not necessary to update s3 code, except the dependency may be
