### ISSUE TITLE
Remove unused functional test suites

### ISSUE THREAD

**Issue by DavidPineauScality** [scality/S3#349]
Currently, two test suites exist that are not run automatically:
 * boto
 * jets3t

We should either remove them, or run them automatically.

It makes sense to remove boto, as we're already testing it through s3cmd.
As for jets3t, I am unsure whether we should remove it, or try to activate/fix it. Activating those means that we'd need to make sure it properly works in our integration/end-to-end testing.

**Comment by LaurenSpiegel** [comment]
I agree that we can remove boto.  As for jets3t, as of 6.2.1 it was replaced with the java sdk tests so we could test streaming v4 auth.  Where are you still seeing jets3t?

**Comment by DavidPineauScality** [comment]
It was on the rel/6.2 branch (I was working on something related to the dependency patcher, so I need the support to start there).
I guess jets3t is a no-discussion since it's already been removed on more recent branches :)

**Comment by LaurenSpiegel** [comment]
@nicolas2bert will be adding some boto tests since he is unable to test some invalid headers with the other clients.  @DavidPineauScality, ok to close this?

**Comment by DavidPineauScality** [comment]
Well, since jets3t has been removed since and boto will be used from now on, I guess yes :)
