### ISSUE TITLE
Package.json files are not patched for our E2E tests

### ISSUE THREAD

**Issue by DavidPineauScality** [scality/S3#359]
Our E2E patching mechanism only patches each project's package.json file.

As such, the individual package.json files of the various functional test suites are not managed. As those tests are used as-is in our E2E scenarios, it is necessary to allow the dependency patcher to fix the dependencies towards our projects (namely Arsenal).

This includes the following work:
- [ ] [Optional] Make tests self-contained (allows cleaning up circle.yml) #358 
- [ ] [Mandatory] Regroup package.json dependencies into project's package.json
- [ ] [Optional] Cleanup legacy stuff from tests

As the aim is to improve the dependency patcher support, we should target rel/6.2

**Comment by LaurenSpiegel** [comment]
@DavidPineauScality, can we close this?

**Comment by DavidPineauScality** [comment]
Yes, with my recent Package.json regroupment it should be good now :)
