### ISSUE TITLE
Docker: SMB Volume support for data and metadata? 

### ISSUE THREAD

**Issue by rusher81572** [scality/S3#368]
Hello, I am trying the following Docker command to have s3data and metadata stored on a samba share.

```
docker run -d --name s3 -e PORT=8000 -p 8000:8000 -v /media/s3-data:/data -v /media/s3-metadata:/metadata registry:5000/s3
```

The error when starting the container is:

```
OpenError: IO error: /metadata/rootDB: Invalid argument
    at /usr/src/app/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:119:34
    at /usr/src/app/node_modules/level/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

The container works fine without the -v options. If I login with interactive mode and create a few test files to verify permissions:
```
docker run -it --name s3 -e PORT=8000 -p 8000:8000 -v /media/s3-data:/data -v /media/s3-metadata:/metadata registry:5000/s3 bash
```

Now I am inside the container. Let's try to create files

```
root@618953d7b024:/usr/src/app# touch /data/test1.txt
root@618953d7b024:/usr/src/app# touch /metadata/rootDB/test2.txt

root@618953d7b024:/usr/src/app# ls -al /metadata/
total 4
drwxrwxrwx 1 root root    0 Nov  8 20:55 .
drwxr-xr-x 1 root root 4096 Nov  8 21:00 ..
drwxrwxrwx 1 root root    0 Nov  8 21:02 rootDB

root@618953d7b024:/usr/src/app# ls -al /data
total 5
drwxrwxrwx 1 root root    0 Nov  8 21:02 .
drwxr-xr-x 1 root root 4096 Nov  8 21:00 ..
drwxrwxrwx 1 root root    0 Nov  8 20:54 0
drwxrwxrwx 1 root root    0 Nov  8 20:54 1
drwxrwxrwx 1 root root    0 Nov  8 20:54 10
drwxrwxrwx 1 root root    0 Nov  8 20:54 100
drwxrwxrwx 1 root root    0 Nov  8 20:54 1000
drwxrwxrwx 1 root root    0 Nov  8 20:54 1001
drwxrwxrwx 1 root root    0 Nov  8 20:54 1002
(Goes on for a long time
```

The test files were able to be created with no issues. I am not sure why the S3 server has trouble starting. Looks like the s3server works fine with -v on the root volume. Just not SMB shares

**Comment by nicolas2bert** [comment]
Hey @rusher81572 
The problem can be that you are not giving the right localData and localMetadata root

Try:

`docker run -­v /media/s3-data:/usr/src/app/localData -­v /media/s3-metadata:/usr/src/app/localMetadata -p 8000:8000 ­-d registry:5000/s3`

**Comment by rusher81572** [comment]
@nicolas2bert  In my Dockerfile, I have the following set:

VOLUME /data
VOLUME /metadata
ENV S3DATAPATH "/data"
ENV S3METADATAPATH "/metadata"

So it should work fine.

The command you gave me is returning:

docker: Error parsing reference: "\u00adv" is not a valid repository/tag.

**Comment by rusher81572** [comment]
On the Mac, I did a test without Docker. I created two symlinks:

lrwxr-xr-x   1 rusher81572  staff     18 Nov  8 14:35 localData -> /Volumes/volume9/1
lrwxr-xr-x   1 rusher81572  staff     18 Nov  8 14:36 localMetadata -> /Volumes/volume9/2

Then npm start

Everything worked fine.

**Comment by ThibaultRiviere** [comment]
@rusher81572  can you try to run it with the ```--privileged``` flag ?

**Comment by rusher81572** [comment]
@ThibaultRiviere Same problem =(
```
# docker run -d --privileged --name s3 -v /media/s3:/data -v /media/s3-md:/metadata  registry:5000/s3
5a0ca65273cafb2d3ccefcf895ddaf304f3fbf399aaac6569ec31172a0004019
```
```
root@rpi-3:/# docker logs -f s3

> s3@1.1.0 start /usr/src/app
> node init.js && node index.js

{"name":"S3","error":{"errno":25,"code":"ENOTTY","syscall":"ioctl"},"level":"warn","message":"WARNING: Synchronization directory updates are not supported on this platform. Newly written data could be lost if your system crashes before the operating system is able to write directory updates.","hostname":"5a0ca65273ca","pid":17}
{"name":"S3","level":"info","message":"Init complete.  Go forth and store data.","hostname":"5a0ca65273ca","pid":17}
{"name":"S3","level":"warn","message":"scality kms unavailable. Using file kms backend unless mem specified.","hostname":"5a0ca65273ca","pid":27}
```

**Comment by ThibaultRiviere** [comment]
It can be an issue because of the mount between your host and the VM used by boot2docker
I'm looking for more information.
Do you have a way to use it as you did but on a linux machine?

**Comment by rusher81572** [comment]
When I opened the issue, it was tested on a Linux machine (raspberry pi) as well as my recent test with the privileged flag.  The mac test referenced earlier in this issue was to rule out any possible file issues with SMB and the S3 server

**Comment by nicolas2bert** [comment]
Have you tried on your Mac with Docker?
With this Docker file 
```
FROM node:4-slim
MAINTAINER Giorgio Regni <gr@scality.com>

VOLUME /data
VOLUME /metadata
ENV S3DATAPATH "/data"
ENV S3METADATAPATH "/metadata"

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN apt-get update \
    && apt-get install -y python git build-essential \
    && npm install \
    && apt-get autoremove -y python build-essential

CMD [ "npm", "start" ]

EXPOSE 8000
```

```
docker build ./ -t 's3'
docker run -d -p 8000:8000 -v /media/s3-data:/data -v /media/s3-metadata:/metadata s3
```

Docker volume worked fine for me.
Have you figured it out?

**Comment by GiorgioRegni** [comment]
I have the issue is the samba share that may be lacking so filesystem operations that we need for the storage to work for S3 Server. Like dirsync for folders. Could you try without SMB just to rule out if it's related to that?
Thanks

**Comment by GiorgioRegni** [comment]
@nicolas2bert I am guessing that you didn't try with a SMB mount point

**Comment by nicolas2bert** [comment]
@GiorgioRegni No I did not. I am going to.
@rusher81572 have you tried without SMB?

**Comment by rusher81572** [comment]
Hello, @nicolas2bert . Just to clarify that I understand what to do next, what do you mean by trying without SMB? I can say with confidence that S3 server works with -v and even with -v on a glusterfs mount.

**Comment by rusher81572** [comment]
If you all want to discuss this on HipChat, I am free all day =)

**Comment by NicolasT** [comment]
LevelDB and SMB (or, at least, the Linux CIFS client, dunno) are not compatible.

Here's what happens when trying to open/create a database:
```strace
...
open("./dat/MANIFEST-000002", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 6
fstat(6, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(6, "V\371\270\370\34\0\1\1\32leveldb.BytewiseComparator", 35) = 35
write(6, "\244\234\213\276\10\0\1\2\3\t\0\3\4\4\0", 15) = 15
open("./dat", O_RDONLY)                 = 7
fsync(7)                                = -1 EINVAL (Invalid argument)
close(7)                                = 0
...
```
After this, the error gets propagated upwards. Or, mapped back to the LevelDB code: https://github.com/google/leveldb/blob/3080a45b626f8ddb474bc5e860796a48b51b3cf0/util/env_posix.cc#L229

Basically, CIFS doesn't seem to provide support for `fsync` on a directory, which makes LevelDB bail out (for good reason, on any 'normal' Linux filesystem).

(I tested using the Python LevelDB bindings, but that makes no difference)

**Comment by lallinger-arbeit** [comment]
For anybody comming across this problem try setting S3DATA_NOSYNC to true. Also increase the initialDelaySeconds when deploying cloudserver via kubernetes.
