### ISSUE TITLE
[ObjectCopy][XMLResponse] bad Date format in LastModified field

### ISSUE THREAD

**Issue by DavidPineauScality** [scality/S3#372]
Testing hadoop against the S3 server, the java code fails when attempting to parse a Date. It looks like it's attemtping to parse it as Iso8601 when it's not formatted this way.

Here is the S3 Logs (trace level) from s3server:
```
{"name":"S3","bucketName":"mybucket","objectKey":"derby93","accessKey":"accessKey1","xml":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><CopyObjectResult><LastModified>Wed, 09 Nov 2016 16:16:12 GMT</LastModified><ETag>&quot;d88d58e233cfba321424c8452ba2a314&quot;</ETag></CopyObjectResult>","time":1478708172757,"req_id":"162a10e21335c36b3f42","level":"trace","message":"xml response","hostname":"c314ca580bc8","pid":57}
```

Here is the output from a s3cmd ObjectCopy
```
DEBUG: Response: {'status': 200, 'headers': {'content-length': '234', 'via': '1.1 ubnt1 (squid/3.4.8)', 'x-cache': 'MISS from ubnt1', 'x-amz-id-2': 'NGblUtou6K8lvXGvmQW4tcZEsnJxRm046qLBhMJTR8cpHRrMaLGcFheFWHSrAdO0wK81auZHH4E=', 'x-cache-lookup': 'MISS from ubnt1:0', 'server': 'AmazonS3', 'connection': 'keep-alive', 'x-amz-request-id': '568CD32D9EF08BD1', 'date': 'Wed, 09 Nov 2016 16:24:52 GMT', 'content-type': 'application/xml'}, 'reason': 'OK', 'data': '<?xml version="1.0" encoding="UTF-8"?>\n<CopyObjectResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LastModified>2016-11-09T16:24:52.000Z</LastModified><ETag>&quot;fac2a668031954664ec5febf2f301c27&quot;</ETag></CopyObjectResult>'}
```

**Comment by alexandre-merle** [comment]
```2016-11-09T16:24:52.000Z``` should be ```2016-11-09T16:24:52Z``` refering to https://en.wikipedia.org/wiki/ISO_8601

**Comment by DavidPineauScality** [comment]
No matter, the thing is:
 * We're returning `Wed, 09 Nov 2016 16:16:12 GMT`
 * S3 actually returns `2016-11-09T16:16:12.000Z`

**Comment by alexandre-merle** [comment]
oh right ^^ don't see the second output is from Amazon :)

**Comment by vrancurel** [comment]
@LaurenSpiegel ?

**Comment by LaurenSpiegel** [comment]
Here is the fix https://github.com/scality/S3/commit/4bf8d5add6d88089893e9a1be8cdfcc35d03ef12

I will add an s3curl test because the node sdk transforms the format (so we didn't see the difference).

**Comment by DavidPineauScality** [comment]
Thanks, I'll notify the original reporter of the ongoing fix. I guess this should be part of the 6.2.4  (if there is one) ?

**Comment by pgueant** [comment]
Looks good. Thanks !

**Comment by LaurenSpiegel** [comment]
fixed by: https://github.com/scality/S3/commit/351619eec868799ef285e95accc1fc1a2f1bdff8
