### ISSUE TITLE
High-availability or Load Balancing?

### ISSUE THREAD

**Issue by rusher81572** [scality/S3#376]
Is it possible to do HA or LB with the S3 server? I love to do this for my home setup per my blog post: https://www.linux-toys.com/?p=1014. 

It does not look like it would be wise to share the data and meta data directories between two separate instances of the S3 server due because of data corruption.

**Comment by nicolas2bert** [comment]
Hey @rusher81572 
Really cool post!
We do not have a High-availability or Load Balancing deployment strategy for our open-source S3server at this stage.

**Comment by rusher81572** [comment]
Thank you very much for the information.
