### ISSUE TITLE
""start must be <= end" error when calling the last CopyPart of a multipart upload request

### ISSUE THREAD

**Issue by cpaul06** [scality/S3#407]
I'm getting the following error:
docker-current[2100]: {"name":"S3","error":"start must be <= end","stack":"Error: start must be <= end\n    
at new ReadStream (fs.js:1653:13)\n    
at Object.fs.createReadStream (fs.js:1608:10)\n
at Object.getFile [as get] (/usr/src/app/lib/data/file/backend.js:90:23)\n
at Object.data.put.get.client.get [as get] (/usr/src/app/lib/data/wrapper.js:65:16)\n
at copyPart (/usr/src/app/lib/api/objectPutCopyPart.js:158:33)\n    
at iterate (/usr/src/app/node_modules/async/lib/async.js:265:13)\n
at Object.async.forEachOfSeries.async.eachOfSeries (/usr/src/app/node_modules/async/lib/async.js:284:9)\n
at goGetData (/usr/src/app/lib/api/objectPutCopyPart.js:155:26)\n    
at fn (/usr/src/app/node_modules/async/lib/async.js:717:34)\n
at /usr/src/app/node_modules/async/lib/async.js:1170:16\n    
at /usr/src/app/node_modules/async/lib/async.js:172:37\n
at /usr/src/app/node_modules/async/lib/async.js:677:43\n    
at /usr/src/app/node_modules/async/lib/async.js:173:37\n
at /usr/src/app/node_modules/async/lib/async.js:1166:30\n    
at /usr/src/app/lib/api/objectPutCopyPart.js:135:28\n
at /usr/src/app/lib/services.js:609:28","level":"fatal","message":"caught error","hostname":"b83b25c4d988","pid":74}

when I'm trying to copy a file (using multipart upload and CopyPart) from one bucket to another using the latest docker image. The file size is 102MB and I have a part size of 100MB

**Comment by nicolas2bert** [comment]
@cpaul06 - We are looking at it.

**Comment by nicolas2bert** [comment]
Hey @cpaul06,

 I think that your S3server Docker container is not up-to-date.

We have replicated the issue using the previous Docker tag (`ae0caa4`), but that it is indeed resolved in the latest (`50f9316`).

To update it:

**1.** Stop your S3server Docker container: `docker stop <CONTAINDER_ID> `
**2.** Remove your S3server Docker container: `docker rm <CONTAINDER_ID>`
**3.** Remove all your S3server Docker images: `docker rmi <IMAGE_ID>`
**4.** Run the up-to-date S3server: `docker run -d --name s3server -p 8000:8000 scality/s3server`

To be sure that your Docker is up-to-date, you can:

**1.** Create a new Bash session in the container `docker exec -it <CONTAINDER_ID> bash`
**2.** Show commit logs:`git log` the first commit shoud be `commit 50f93164e17b7af32494d2f28a9ca20e228caea1`

**Comment by nicolas2bert** [comment]
Hey @cpaul06, does it help?

**Comment by cpaul06** [comment]
By following the steps you mentioned, I now have the latest image (commit 50f93164e17b7af32494d2f28a9ca20e228caea1) and the issue is no longer present.
Thanks @nicolas2bert
