### ISSUE TITLE
significantly lower performance on streaming V4 than V2

### ISSUE THREAD

**Issue by mastachand** [scality/S3#414]
Hi,

I'm running S3 GA6.2.3 with docker 1.10.3

I've been testing a backup system against S3, and i've seen significantly worse performance using streaming V4 rather than simple v2. 
The response times from S3 are 4 to 5 times lower using V2. Avg response times are an order of magnitude slower on V4. I've attached a sample of logs that shows an S3/sproxydclient/nginx/sproxyd log stack for both V4 and V2 puts. The first log is V4, the second is V2.

Can you help?

-Marc

[rman_test_v4.txt](https://github.com/scality/S3/files/598814/rman_test_v4.txt)

**Comment by mastachand** [comment]
Update: When this happens, i see node processes shoot up to 99% CPU on the servers handling the requests.

**Comment by LaurenSpiegel** [comment]
Removal of buffer.concat increased performance significantly: https://github.com/scality/S3/pull/419

According to @mastachand's estimates after the removal of buffer.concat streaming v4 is about 3.5 slower than v2 on the backup app he is running.

**Comment by GiorgioRegni** [comment]
Let's keep it as is for now and revisit if needed in the future.
