### ISSUE TITLE
"One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag" error when multipart uploading a 7GB file

### ISSUE THREAD

**Issue by cpaul06** [scality/S3#444]
I'm trying to multipart upload a 7Gb file using 5MB parts (total parts count = 1434).
When calling CompleteMultipartUpload, I'm getting the error: "One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag"
I'm getting the same error when trying to multipart upload a 10Gb or 40Gb file.

However when I multipart upload a 200Mb or 1Gb file, everything works fine.

**Comment by nicolas2bert** [comment]
Hey @cpaul06 - 

We are going to look at your issue. 

Thanks.

**Comment by cpaul06** [comment]
@nicolas2bert - Here is the code with which I could reproduce the issue:
[CompleteUpload.txt](https://github.com/scality/S3/files/633098/CompleteUpload.txt)

**Comment by cpaul06** [comment]
@nicolas2bert - Using a part count above 1000 in the attached code, I get the error mentioned in the title: "One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag" .
But with a value smaller than 1000 (for ex: 3, 50, 999), I'm getting: "Your proposed upload is smaller than the minimum allowed object size."

**Comment by nicolas2bert** [comment]
@cpaul06 - I am currently looking at it and trying to reproduce your issue.
Can you give me more information about your system, memory size and storage space?

Thank you.

**Comment by LaurenSpiegel** [comment]
@cpaul06, is it possible that putting one of your parts resulted in an error so you added to your list of etags an undefined and then tried to complete the MPU with a list of etags that included undefined?  Do you have an errors in your log?  Could you add a log to your script to check for any errors?

Regarding your "upload is smaller" comment, if an object size is less than 5 MB, that error is returned.  Were your part sizes (other than the last part) greater than 5 MB?

Thanks!

**Comment by cpaul06** [comment]
@LaurenSpiegel - Please disregard the "upload is smaller" comment, it was my fault; as you said not all the parts were greater than 5MB (except the last)

When do you think scality/Arsenal#165 will be available in this repository and then in the docker container image?

**Comment by LaurenSpiegel** [comment]
Hi @cpaul06, thanks for the clarification.  We are currently testing the arsenal fix and the new docker should be out next week.

**Comment by nicolas2bert** [comment]
Hey @cpaul06 - this issue has been fixed. Please run the `lastest` / `ece570f`  S3 server Docker image: https://hub.docker.com/r/scality/s3server/
