### ISSUE TITLE
Can't list parts from a given PartNumberMarker

### ISSUE THREAD

**Issue by cpaul06** [scality/S3#445]
I have a small file which I multipart uploaded using 7 parts of size 5MB.
When I try to list parts starting from part number 2, the response doesn't return anything (no parts and the response isn't truncated).

I attached a small C# example of how I'm trying to get the uploaded parts.
[ListParts.txt](https://github.com/scality/S3/files/631582/ListParts.txt)

If I set PartNumberMarker to null (default), then I get all the parts as expected.
However this becomes a problem when the number of uploaded parts grows beyond the 1000 limit for one ListParts operation.

**Comment by nicolas2bert** [comment]
Thanks for your feedback - we are working on it. 
I will let you know once this issue is fixed.
