### ISSUE TITLE
COMPAT: unreadable header(s) return AccessDenied on AWS

### ISSUE THREAD

**Issue by nicolas2bert** [scality/S3#447]
On **ceph/s3-tests**, this test fails:
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_md5_unreadable`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_contenttype_unreadable`
- `FAIL: s3tests.functional.test_headers.test_object_create_bad_date_unreadable_aws4`

**Comment by LaurenSpiegel** [comment]
Closing issue since node already checks header characters (other than small ASCII range) and adding an additional check impacts performance.
