### ISSUE TITLE
Error response compat for bucket already owned by you

### ISSUE THREAD

**Issue by LaurenSpiegel** [scality/S3#475]
On AWS S3, when there is no location constraint specified (i.e. region is us-east-1), creating a bucket that is already owned by you generates a no-op 200 OK response. We send a 409 (like the other regions do). 

We should respond like AWS does.  Need to test what the response is if us-east-1 is explicitly specified.

Should target rel/6.3 branch.

**Comment by LaurenSpiegel** [comment]
The AWS behavior:

If you create a bucket in us-east-1 (so us-east-1 location constraint) and then try to recreate in us-east-1 => 200

If you create a bucket in us-east-1 and try to recreate in us-west-1 => 409

If you create a bucket in us-west-1 and try to recreate in us-east-1 => 409

If you create in us-east-1 and specify location as us-west-1 and try to recreate in us-east-1 => 409

**Comment by rahulreddy** [comment]
So this means all we have to do is add one check for error?
If we get a PUT bucket on us-east-1, if we get BucketAlreadyExists from MD we respond back with 200.

**Comment by LaurenSpiegel** [comment]
To return a 200, 3 things must hold:
1) bucket originally created with us-east-1 location
2) second request is directed to us-east endpoint
3) second request does NOT contain a location constraint request for another region

**Comment by rahulreddy** [comment]
Ok.

**Comment by ttvi** [comment]
I don't know if we should follow AWS' actual behavior or their API specifications. Some of their actual behavior is absurd, such as the `MaxKeys` in the result of an object listing is described as "The maximum number of keys returned in the response body.", but it's the user input `max-keys` in reality according to Lauren/GG's test.
Should we be bold (stick to the logical specifications) or be evil (follow the ugly truth to be "totally compatible")?

**Comment by ttvi** [comment]
Actually in this case their behavior of returning 200 is inline with their specifications for `BucketAlreadyOwnedByYou`, but it's true for the region us-east-1 only http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html.

**Comment by LaurenSpiegel** [comment]
fixed here: https://github.com/scality/S3/commit/5fe55f5dccd8f23478100858ac318b76d975b6f1#diff-92fd6b935e7cc55dcbd3440a88fe8082
