### ISSUE TITLE
continuation-token and start-after are not working

### ISSUE THREAD

**Issue by nicored** [scality/S3#490]
Hi,

I am building a go application and I am trying to paginate through the list of objects I get back.

```
GET /nico-test/?list-type=2&max-keys=500&prefix=buckets%2Fbucket_9%2Fcad%2F&start-after=buckets%2Fbucket_9%2Fcad%2F123.pdf
```

I found out that the continuationToken is not sent back in the API response.

Both work with my real AWS S3 bucket.

Thanks for your help.

**Comment by nicored** [comment]
Talking to a friend about this. And he's going to write support for continuationToken.
The idea would be to return an md5 of the last object key listed in the response, so that the next call that includes that md5 (token), will return the list of objects that come after it. And nothing, or empty string if there's nothing else to return. Ideas?

**Comment by nicolas2bert** [comment]
Hey @nicored,

We are not supporting [GET Bucket (List Objects) Version 2](http://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html) yet.

Please look at [GET Bucket (List Objects) Version 1](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) .
Can `NextMarker` solve your issue?

**Comment by nicored** [comment]
Thanks for the response. Do you have an ETA or is it not in your roadmap yet? Myself or a colleague could possibly find some time to implement it after the new year.

**Comment by nicolas2bert** [comment]
@nicored - You are welcome.
Feel free to contribute. Don't forget to sign your work: https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by LaurenSpiegel** [comment]
@nicored, if you want to work on an implementation that would be great.  The most straightforward approach might be to use the next marker from the version 1 listing and use it as the continuation token.  We don't really have a need for an opaque continuation token since we are not caching the listing.

**Comment by nicored** [comment]
No worries. Will get started on the 1st.
