### ISSUE TITLE
How to configure against a custom dns?

### ISSUE THREAD

**Issue by xmonader** [scality/S3#491]
Hello, Thanks for the awesome work.

I'm trying use caddy as a reverse proxy to reach s3 server.
I'm not sure how to configure the regions or what might be the cause of the problem 

I'm using s3cmd and It works fine against the if i set the host_base/bucket_base to the `ip` 
If i switch set the domain name 

I usually get 

```
ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided.
``` 
or 
```
ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.

````

Thanks in advance

**Comment by nicolas2bert** [comment]
Hey @xmonader - 

If your issue is about how to specify your own host name, here is a section that might help you. https://github.com/scality/S3/blob/master/DOCKER.md#specifying-your-own-host-name

**Comment by xmonader** [comment]
@nicolas2bert  thanks :) 
Maybe it was a glitch. i redeployed it and tried again setting my custom domain in us-east-1 region and it worked -deployed like 5 times or so-
