### ISSUE TITLE
s3 worker crashing (assertion error)

### ISSUE THREAD

**Issue by msegura** [scality/S3#548]
It seems the s3 worker process might be crashing. This could be related to a metadata outage.

The stack trace is :

```
{"name":"S3",","error":"null == true","stack":"
AssertionError: null == true
    at process.target._send (internal/child_process.js:519:5)
    at process.<anonymous> (internal/child_process.js:485:12)
    at emitTwo (events.js:92:20)
    at process.emit (events.js:172:7)
    at internal/child_process.js:696:12
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
","level":"fatal","message":"caught error","hostname":"redacted","}
```

**Comment by ploki** [comment]
Seems related to https://github.com/nodejs/node/issues/4205

**Comment by ploki** [comment]
fixed in node by this commit https://github.com/nodejs/node/commit/57a51a00e8472bae21bc0a4767535bd3c55e592c

**Comment by ploki** [comment]
seems to be related to #546

**Comment by nightfox02** [comment]
Attached S3 log for 10.64.50.106 approx one minute prior to event at 

1485099379670

Assuming that this timestamp is in milliseconds:
GMT: Sun, 22 Jan 2017 15:36:19.670 GMT
Your time zone: 1/22/2017, 7:36:19 AM GMT-8:00
[10.64.50.106.minute.txt](https://github.com/scality/S3/files/722433/10.64.50.106.minute.txt)

**Comment by vrancurel** [comment]
It is included in 6.0 onwards

**Comment by ploki** [comment]
@vrancurel and since v4.2.5

**Comment by LaurenSpiegel** [comment]
per discussion with @ploki there still seems to be a race condition in node around here:
https://github.com/nodejs/node/pull/4418/files#diff-f45eb699237c2e38dc9b49b588933c11R519
