### ISSUE TITLE
COMPAT: should not check vault credentials for get/head website requests

### ISSUE THREAD

**Issue by electrachong** [scality/S3#553]
UPDATE: @nicolas2bert fixed the following behavior in https://github.com/scality/S3/issues/573 but we realized his refactor involved checking auth credentials, when we have not tested AWS behavior for website endpoint requests with credentials. Testing reveals we should not be making checking authentication credential and should only check if objects and buckets have public-* acls.

-----------------------------------------------

While testing cors headers responses for website endpoints, I found AWS responds with the following to requests for an object that does not exist (on bucket with public-read-write ACLs).

```
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: test</li>
<li>RequestId: BC20E1D1388DFB25</li>
<li>HostId: NX+GRaKR27CCl/kiMa4iiF/KDApIrzT299WVHVgEhuG8o2X94FIfE6R/C+MFYSpiFvZRiufWxf8=</li>
</ul>
<hr/>
</body>
</html>
```

S3 current response:
```
<html><head><title>403 Forbidden</title></head><body><h1>403 Forbidden</h1><ul><li id='code'>Code: AccessDenied</li><li id='message'>Message: Access Denied</li><li>BucketName: bucketwebsitetester</li><li>RequestId: 8d95b84118e1695f47aa</li></ul><hr></body></html>
```

I remember we believed this was the appropriate response when testing/developing the website endpoint responses before, so will want to investigate the reason for that belief and if we have any other tests to corroborate a 403 AccessDenied response in certain scenarios (e.g. different ACLs).

**Comment by LaurenSpiegel** [comment]
Please test with wrong credentials against real AWS on a bucket endpoint with no such key.

**Comment by electrachong** [comment]
1. Wrong credentials against real AWS on bucket endpoint with no such key returns 404 if bucket is public, 403 if bucket is private (same behavior as without credentials).
2. The error behavior seems only based on whether the resources (buckets, object, and error objects) are public/private. For instance, `403 Access Denied` results from trying to access a private bucket website are not changed by sending valid credentials of an account authorized to access that bucket in the request. And the success of accessing a public bucket website is not impacted by sending invalid credentials. So we do want to refactor the website get / head apis (since they currently use `authInfo` when we only want to check if object/bucket is authorized with acls).
