### ISSUE TITLE
Abort MPU returns 404 for all regions when Upload Id doesn't exist

### ISSUE THREAD

**Issue by rahulreddy** [scality/S3#568]
Tests reveal that AWS S3 returns 404 for us-east-1 and 204 for all other regions. We have a customer complaining about this incorrect behavior. We could leverage `usEastBehavior` to toggle the legacy behavior.
The fix should be against `6.2.5`.

**Comment by LaurenSpiegel** [comment]
As discussed, we will return a 204 in all cases in 6.2.  In 6.3, where we have the usEastBehavior concept, we will toggle.
