### ISSUE TITLE
Support Signed S3 ObjectPUTs

### ISSUE THREAD

**Issue by tjsail33** [scality/S3#57]
Hello - 

I'm trying to use your container to mock S3 locally, and so far its working great, so thank you for that. The one thing it is missing that i've found is support for browser to S3 uploads using signed PUT urls. 

Here's the AWS docs on generating said urls: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

I'm seeing the following in my console when trying to do the PUT:
```
XMLHttpRequest cannot load http://192.168.99.100:8005/test/planner/corp-prod-local-dev/attachments/42a…92630&Signature=GqVo%2Fa9d19%2BsHj3%2FcCcIkyu7lXQ%3D&x-amz-acl=public-read. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 405.
```

Here's the output of the Chrome network tab:
```
Request URL:http://192.168.99.100:8005/test/local-dev/attachments/42ae42a6-93b9-44d6-a0da-3aad235eed4a/screen_shot_2016-06-15_at_8.46.36_pm.png?AWSAccessKeyId=accessKey1&Content-Type=image%2Fpng&Expires=1466092630&Signature=GqVo%2Fa9d19%2BsHj3%2FcCcIkyu7lXQ%3D&x-amz-acl=public-read
Request Method:OPTIONS
Status Code:405 Method Not Allowed
Remote Address:192.168.99.100:8005
Response Headers
view source
Connection:keep-alive
Content-type:application/xml
Date:Thu, 16 Jun 2016 15:56:10 GMT
server:AmazonS3
Transfer-Encoding:chunked
x-amz-id-2:3e25eaca2fe42c90930d
x-amz-request-id:3e25eaca2fe42c90930d
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Access-Control-Request-Headers:accept, content-type
Access-Control-Request-Method:PUT
Connection:keep-alive
Host:192.168.99.100:8005
Origin:http://localhost:8000
Referer:http://localhost:8000/planner/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Query String Parameters
view source
view URL encoded
AWSAccessKeyId:accessKey1
Content-Type:image/png
Expires:1466092630
Signature:GqVo/a9d19+sHj3/cCcIkyu7lXQ=
x-amz-acl:public-read
```

Any ideas?

**Comment by michael-zapata** [comment]
Hello @tjsail33,

Great to see the server put to good use!

I can see in your report that you are using `Transfer-Encoding:chunked` which we do not support at the moment, that may be the issue at hand.

**Comment by NicolasT** [comment]
It looks like you're using **XHR** to **PUT** an object, which has certain security mechanisms in place, one among them called **CORS**, or _Cross Origin Resource Sharing_. It's a way for a service to allow (or disallow) access to it through **XHR** or similar means from an application served by a different host. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

This is checked before the actual **XHR** request is issued through an **OPTIONS** request to the same endpoint by the browser. At this point, the target service should return a _Access-Control-Allow-Origin_ header listing the hosts serving applications that are allowed to access this service (S3Server in this case).

To overcome the current limitation, the S3Server could be adapted to return an `Access-Control-Allow-Origin: *` header upon such **OPTIONS** requests, though that can be a security issue in production setups, so may need to be configurable.

Once **CORS** is working, there'd still be the issue @michael-zapata refers to :wink:

**Comment by tjsail33** [comment]
Hi @NicolasT and @michael-zapata, thanks so much for getting back to me. Both of your comments make total sense. I think the CORS comment is the easiest hurdle to clear, as I can add from end configs to not use `chunked` when doing the upload to the local S3 container. Thoughts on whether that would be a functional workaround?

**Comment by LaurenSpiegel** [comment]
Hi, @tjsail33 chunked encoding should not be an issue.  @michael-zapata was referring to streaming v4 auth which we do not support yet but that should not hold you back.  I believe the only client that even supports streaming v4auth is the java sdk.  Let us know how it goes.
