### ISSUE TITLE
getSignedUrl

### ISSUE THREAD

**Issue by jacksonStone** [scality/S3#583]
I've found this issue: https://github.com/scality/S3/issues/57 which has a comment indicating that CORs related features are not supported. Is this still the case?

So when using the AWS SDK, I want to preform direct downloads using the getSignedUrl. I have used the putBucketCors api command and updated everything accordingly on a bucket I've created.

`S3.putBucketCors({
						Bucket: <bucket_name>,
						CORSConfiguration: {
							CORSRules: [
								{
									AllowedMethods: ["GET"],
									AllowedOrigins: ["*"],
									AllowedHeaders: ["*"],
									MaxAgeSeconds: 60
								},
							]
						}})`

However, I still get a: _No 'Access-Control-Allow-Origin' header is present on the requested resource._ When I attempt to make a request to the signed URL.

When I have an identical bucket configuration on my personal AWS account, I am able to preform direct downloads as expected, however when running this in docker, it seems the bucket cors configuration is not respected.

Is direct upload and download still  unsupported behavior?

**Comment by electrachong** [comment]
Hi @jacksonStone,

We've been working on adding CORS functionality and just merged some CORS-related features a few days ago. Have you pulled the most recent commits from master from the github repo? If not, give it a shot and let us know if you're still having problems detecting the `Access-Control-Allow-Origin` response header.

**Comment by electrachong** [comment]
Actually, I just checked and it looks as if we may not have been able to make a forwardport to push the relevant commits to the master branch in the S3 repository yet. If you would like, you can try to use the [rel/6.4](https://github.com/scality/S3/tree/rel/6.4) branch to test the CORS functionality we have implemented while we get that merged into master.

**Comment by jacksonStone** [comment]
That works!! Thanks so much!

**Comment by electrachong** [comment]
Glad to hear! Thanks for trying out S3!

**Comment by DeepDiver1975** [comment]
looks like the latest docker image does not hold this fix - can I ask you to update the image?
