### ISSUE TITLE
Path Style url

### ISSUE THREAD

**Issue by BLaurent** [scality/S3#60]
Hi,

I am using Jcloud to acces s3 server bit with path style url, I got 400 status all the time
and xml as response.

Is path-style supported ?

Regards
B

**Comment by DavidPineauScality** [comment]
Hello @BLaurent,
Yes it is. Do you have any verbose/debug output that we could use to help you ? Could you also give us the exact error XML that you get ?

**Comment by BLaurent** [comment]
Thanks I figure it out it was an acl issue. 
Regards
