### ISSUE TITLE
Unhandled exception if utapi is not configured

### ISSUE THREAD

**Issue by densaidisk** [scality/S3#613]
In lib/utapi/utilities.js, `pushMetric `definition explicitly `return utapi.pushMetric(...),` even if utapi is not configured (and thus equals to `{ component: 's3' }` as defined in lib/Config.js).

That cause an unhandled exception when trying to use the function and prevent, in my case, the S3 server from responding (although the action is well realized).

**Comment by rahulreddy** [comment]
@densaidisk We are in the process of removing assertions in S3 related to Utapi unless Utapi config is defined. I am a bit confused by your question, are you trying to use the method `pushMetric` or did get an uncaught exception when you pulled in new code? If you just pulled master, I recommend re-installing your node_modules as utapi may be out of date.

**Comment by rahulreddy** [comment]
Fixed by  https://github.com/scality/S3/pull/612

**Comment by densaidisk** [comment]
I had just pulled master.. but now, by updating and re-installing my node_modules, everything works.

Thank you
