### ISSUE TITLE
Docker : Specifying your own host name

### ISSUE THREAD

**Issue by Tiduster** [scality/S3#654]
Hi !

To correct the InvalidURI error returned by Scality when you use your own host name, I try to follow this documentation: https://github.com/scality/S3/blob/master/DOCKER.md#specifying-your-own-host-name.

Unfortunately, I think its deprecated since https://github.com/scality/S3/commit/2fbcdf35c00f9421b52ed0fc24823ac31cea98e3

To correct my issue, I added my hostname to the restEndpoints section:

```
    "restEndpoints": {
        "localhost": "file",
        "127.0.0.1": "file",
        "scality-s3.blueehp.eu": "file",
        "s3.docker.test": "scality-us-west-1",
        "127.0.0.2": "aws-us-east-1",
        "s3.amazonaws.com": "aws-us-east-1"
    },
```
It's working perfectly, but I don't know if this is the recommended way.

Best Regards,

**Comment by nicolas2bert** [comment]
Hey @Tiduster -
We are in the process of changing the config so the docker on docker hub should not have these changes. 
If you are building your own Docker image, then you are right that you need to update the `restEndpoints` as you have done and our documentation will be updated shortly.

Best Regards,

**Comment by Tiduster** [comment]
Understood!

And yes, I built my own image, I change it a little bit.

Thanks for the quick response.
