### ISSUE TITLE
COMPAT: AWS InvalidRange (Spark/Hadoop s3a)

### ISSUE THREAD

**Issue by stergiotis** [scality/S3#660]
Spark/Hadoop's FileUtils.copyMerge(...) method is unable to merge files which have sucessfully been created using the s3a filesystem.
A minimal example:
```scala
import java.net.URI
import org.apache.hadoop.fs.{Path,FileSystem,FileUtil}
import org.apache.hadoop.conf.Configuration

val hadoopConfig = sc.hadoopConfiguration
hadoopConfig.set("fs.s3a.impl","org.apache.hadoop.fs.s3a.S3AFileSystem")
hadoopConfig.set("fs.s3a.access.key","accessKey1")
hadoopConfig.set("fs.s3a.secret.key","verySecretKey1")
hadoopConfig.set("fs.s3a.endpoint","s3endpoint.com")
hadoopConfig.set("fs.s3a.connection.ssl.enabled","false")

val filePath="s3a://mybucket/example"
sc.parallelize(Array(1,2,3)).saveAsTextFile(filePath)
val mergedFilePath=filePath+".txt"
FileUtil.copyMerge(FileSystem.get(new URI(filePath), hadoopConfig), new Path(filePath),
                   FileSystem.get(new URI(mergedFilePath), hadoopConfig), new Path(mergedFilePath),
                   false, hadoopConfig, null)
```
raises:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 416, AWS Service: Amazon S3, AWS Request ID: 6d987f1d4b28b36a9707, AWS Error Code: InvalidRange, AWS Error Message: The requested range cannot be satisfied.
  at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:798)
  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:421)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3528)
  at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1111)
  at org.apache.hadoop.fs.s3a.S3AInputStream.reopen(S3AInputStream.java:91)
  at org.apache.hadoop.fs.s3a.S3AInputStream.openIfNeeded(S3AInputStream.java:62)
  at org.apache.hadoop.fs.s3a.S3AInputStream.read(S3AInputStream.java:156)
  at java.io.DataInputStream.read(Unknown Source)
  at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:85)
  at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:59)
  at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:119)
  at org.apache.hadoop.fs.FileUtil.copyMerge(FileUtil.java:400)
  ... 50 elided
```
Component versions:
Scality/s3 commit 626596dcd54afa5e0b6ca3589a51737560895326 (8th March 2017)
spark 2.1
hadoop-aws-2.7.3
aws-java-sdk-1.7.4

**Comment by LaurenSpiegel** [comment]
@stergiotis, thanks for the code snippet. I reproduced the issue and the crux of the problem is that the java sdk/spark/hadoop is sending an invalid range request and Scality S3 is responding with a 416 while AWS S3 just ignores the invalid range and returns the whole object.  We will update our behavior to conform to AWS.  

These are the request headers from the bad request:
  headers:
   { host: '127.0.0.1:8000',
     authorization: 'AWS accessKey1:rzAMIEyR/trDp375S4RkaRtxdaw=',
     'user-agent': 'aws-sdk-java/1.7.4 Linux/4.4.39-moby OpenJDK_64-Bit_Server_VM/25.121-b13/1.8.0_121',
     range: 'bytes=0--1',
     date: 'Wed, 22 Mar 2017 20:14:49 GMT',
     'content-type': 'application/x-www-form-urlencoded; charset=utf-8',
     connection: 'Keep-Alive' },

'bytes=0--1' is not a valid range per the rfc -- https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35

**Comment by stergiotis** [comment]
@LaurenSpiegel Thank you very much for your quick response and linking to the relevant section in the RFC. 
I think the following justifies the implemented behaviour of Amazon's S3 server:
>  The recipient of a byte-range- set that includes one or more syntactically invalid byte-range-spec values MUST ignore the header field that includes that byte-range- set.

Negative numbers in the byte range are, if I read the EBNF contained in the RFC correctly always syntactically invalid.

**Comment by stergiotis** [comment]
Setting `err` to `null` when `err.invalidRange` is set in the callback of `api.callApiMethod('objectGet', ...)` (file `lib/routes/routeGET.js`) does indeed solve this issue.

**Comment by jonathan-gramain** [comment]
Indeed, HTTP spec is a bit blurry about it but normally 416 errors are reserved for a *syntactically correct* range request which request is completely outside the object range. The syntactically incorrect range header should indeed be just silently ignored and a 200 should be returned instead with the full contents.

**Comment by nicolas2bert** [comment]
Here the issue is that java sdk/spark/hadoop are adding an **empty** object (without data) to a bucket with **invalid** range request.
- AWS S3 is responding the empty object
- S3 server is responding with a 416 InvalidRange
