### ISSUE TITLE
Location Constraint Info is invalid.

### ISSUE THREAD

**Issue by amarcionek** [scality/S3#669]
Anyone seeing this error when trying to upload an object?  Getting it with CloudBerry and S3Browser and latest build (7 days ago.)

`{"name":"S3","clientIP":"::ffff:192.168.20.1","clientPort":19601,"httpMethod":"PUT","httpURL":"/kscott1/A79F758FD4.DIF","time":1490722748203,"req_id":"7d4208edd8b87f01cd8c","level":"info","message":"received request","hostname":"22370bf410a8","pid":49}
{"name":"S3","bucketName":"kscott1","objectKey":"A79F758FD4.DIF","bytesReceived":2052592,"bodyLength":2052592,"accessKey":"accessKey1","bytesSent":200,"clientIP":"::ffff:192.168.20.1","clientPort":19601,"httpMethod":"PUT","httpURL":"/kscott1/A79F758FD4.DIF","contentLength":2052592,"httpCode":400,"time":1490722748206,"req_id":"7d4208edd8b87f01cd8c","elapsed_ms":3.303361,"level":"info","message":"responded with error XML","hostname":"22370bf410a8","pid":49}
`

**Comment by nicolas2bert** [comment]
Hey @amarcionek - Has `192.168.20.1` been listed in the `restEndpoints` section in your config.json?

Exemple:
_in S3/config.json_
```
"restEndpoints": {
     "192.168.20.1": "us-east-1"
},
```

Note: Please make sure that "us-east-1" is listed in your S3/locationConfig.json

More info: https://github.com/scality/S3#location-configuration

**Comment by amarcionek** [comment]
I should have been a bit more specific. This is from the latest docker image built 7 days ago: https://hub.docker.com/r/scality/s3server/tags/   

I could probably find a way to edit the locationConfig.json file inside of it after running the image (although neither nano nor vi is in the container), but shouldn't the container really be immutable? IOW, you would want people to run it out of the box without any configuration? The prior image (e2a2574) doesn't exhibit this issue.

**Comment by nicolas2bert** [comment]
@amarcionek - Ok - we are going to update it so you won't need to change the config.

**Comment by amarcionek** [comment]
Thanks for the help!

**Comment by nicolas2bert** [comment]
@amarcionek The Docker image has been updated with a fix - please pull the latest (1fcb189) S3 server Docker image.
Keep us updated - thanks.

**Comment by amarcionek** [comment]
I can confirm this now works. THANKS!
