### ISSUE TITLE
Unable to deploy the S3 server as docker container on a Raspberry Pi 3

### ISSUE THREAD

**Issue by christianbaun** [scality/S3#701]
The docker container of S3 Server does not start on a Raspberry Pi 3 with Raspbian (Debian Jessie 8.0).

    $ docker run -d --name s3server -p 8000:8000 scality/s3server

    $ docker ps
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

    $ docker logs s3server
    standard_init_linux.go:178: exec user process caused "exec format error"

I think this issue is caused by the ARM architecture of the single board computer. 

Some system information:

```
$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:22:23 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:22:23 2017
 OS/Arch:      linux/arm
 Experimental: false

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

$ uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux
```

**Comment by LaurenSpiegel** [comment]
Hi @christianbaun, it doesn't look like docker images generally run on raspberry pi off the shelf.  See: http://blog.alexellis.io/getting-started-with-docker-on-raspberry-pi/

The post references that docker has experimental arm images including one for node here: 
https://hub.docker.com/r/armhf/node/ 

Based on the blog post, if you change the "from" line in our dockerfile from regular node6slim to the arm node6 slim from the link above and build the modified image it should work. Will you please let us know if you get it to work? I'll see if anyone on our team has a raspberry pi to play with as well.

**Comment by rusher81572** [comment]
Hello @christianbaun.

I use S3 Server on the Raspberry Pi v3. Before you get started, please ensure that you have a 1 GB swap file at a minimum. We do not currently have an ARM version of S3 Server on Docker Hub. However, please check out my blog post on how to make your own Docker Hub image located here: https://www.linux-toys.com/?p=1014

For it to work on the Raspberry Pi, simply change the following line in the Dockerfile:

Replace:
```
FROM ubuntu
```
With
```
FROM armv7/armhf-ubuntu
```

**Comment by LaurenSpiegel** [comment]
Closing. Let us know if you are still having an issue.

**Comment by christianbaun** [comment]
Hello all,

I tried to deply the S3 Server again on a fresh Raspbian from March 2017 on a RasPi3 with these npm and nodejs versions:

    $ curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    $ sudo apt-get install -y nodejs
    
    $ npm -version
    3.10.10
    $ nodejs --version
    v6.10.2

The output of `npn install` contains some warnings, but it does not fail.

`npm start` fails at some point. And in effect, the service is not running. 

I attached the output of both commands. 

I gave Docker and `armv7/armhf-ubuntu` a try, but this did not change the situation.

[output_of_npm_install.txt](https://github.com/scality/S3/files/965930/output_of_npm_install.txt)
[output_of_npm_start.txt](https://github.com/scality/S3/files/965931/output_of_npm_start.txt)

**Comment by LaurenSpiegel** [comment]
@christianbaun, it looks like your device is out of memory:

FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
{"name":"S3","time":1493444656881,"error":"Callback function \"bound _call\" timed out.","stack":"Error: Callback function \"bound _call\" timed out.\n    at Timeout.timeoutCallback [as _onTimeout] (/home/pi/S3/node_modules/arsenal/node_modules/async/dist/async.js:4724:21)\n    at ontimeout (timers.js:380:14)\n    at tryOnTimeout (timers.js:244:5)\n    at Timer.listOnTimeout (timers.js:214:5)","workerId":1,"workerPid":2568,"level":"fatal","message":"caught error","hostname":"raspberrypi","pid":2568}

**Comment by rusher81572** [comment]
@christianbaun Did you create a 1 GB swap file?  Also, please ensure that no other memory intensive applications are running. Basically S3 Server should be the only application running on the Pi due to it's low system resources.

**Comment by christianbaun** [comment]
Problem solved. 1 GB of main memory is not enough and the missing Swap file caused the issue. Thanks a lot for your help.

**Comment by rusher81572** [comment]
No problem @christianbaun, glad to help. I hope that you enjoy using S3 Server.
