### ISSUE TITLE
No error on invalid MaxKeys for Get object on bucket

### ISSUE THREAD

**Issue by YiuRULE** [scality/S3#75]
When we call with a bucket with an invalid MaxKeys integer (like -1), the server doesn't return an error but continue like it was a valid argument.

```
const params = {
    Bucket: 'valid-bucket-name',
    MaxKeys: -1
};
bucketUtil.s3.listObjects(params, (err, data) => { });
```

On the official amazon S3 server, this code return an error who tell that you must use a MaxKeys values who are between 1 and 2147483647, but in this server, no error is return and we have our list of keys.

**Comment by nicolas2bert** [comment]
Hey @YiuRULE . I did a PR in order to fix this issue,

Thanks
