### ISSUE TITLE
canonical

### ISSUE THREAD

**Issue by bcburkhart** [scality/S3#783]
# Issue template

If you are reporting a new issue, make sure that we do not have any
duplicates already open. You can ensure this by searching the issue list for
this repository. If there is a duplicate, please close your issue and add a
comment to the existing issue instead.

## General support information

GitHub Issues are reserved for actionable bug reports and feature requests.
General questions should be sent to the
[S3 scality server Forum](http://forum.scality.com/).

## Bug report information

(delete this section if not applicable)

### Description

Briefly describe the problem you are having in a few paragraphs.

### Steps to reproduce the issue

Please provide steps to reproduce, including full log output

### Actual result

Describe the results you received

### Expected result

Describe the results you expecteds

## Feature Request

(delete this section if not applicable)

### Proposal

Describe the feature

### Current behavior

What currently happens

### Desired behavior

What you would like to happen

### Use case

Please provide use cases for changing the current behavior

**Comment by LaurenSpiegel** [comment]
No issue stated. Please reopen with description of issue.
