### ISSUE TITLE
MongoDB instead of levelDB for metedata storage

### ISSUE THREAD

**Issue by hosseinko** [scality/S3#824]
Hello

Is there any plans in you schedule to use Mongo DB as a metadata storage instead of levelDB? If not is there any guide on how to replace LevelDB with Mongo DB correctly?

**Comment by LaurenSpiegel** [comment]
Hi @hosseinko, we do not have any current plans to use Mongo DB. If you would like to give it a go, you would have to switch out references to level and sublevel in here and translate the api calls to the appropriate mongo api calls in this file -- https://github.com/scality/Arsenal/blob/master/lib/storage/metadata/file/MetadataFileServer.js

Let us know how it goes.

**Comment by hosseinko** [comment]
@LaurenSpiegel Thanks for your reply. I checked your suggested solution and I found that I need to have a key-value like db in MongoDB in order to store data on it. If it is true, every time I want to fetch data from mongo, I have to fetch all data stored for the given key and then filter them with scality algorithms to pull out needed data. As time passes and size of data increases, it will affect performance very much however if I use aggregates to filter data, the result will be ready way much faster. Is there any other solution to solve performance problems like this?

**Comment by LaurenSpiegel** [comment]
I have not used mongo very much. Does the performance suffer when a collection grows beyond a certain size? Note that each time a key is put, you are not growing the data for that object, you should overwrite it and the size of the metadata is pretty limited.  You can see the different metadata models here: https://github.com/scality/Arsenal/pull/299

**Comment by hosseinko** [comment]
@LaurenSpiegel Sorry for the delay. The problem is size of metadata for files of a bucket. Consider a bucket with more than 20000 files. In MongoDB I create a collection for each bucket in order to store metadata of its files. In this situation every time I want to get a file metadata of this bucket, I have to fetch all 20000 documents and filter them by js filter one by one in scality. In my idea this will affect performance however if I use aggregates it will be done more faster and with less memory and cpu usage taking benefit from indexing and other mongodb features. I was thinking to add a file in /lib/metadata and add mongo db in metadata backend and create aggregate queries using parameters but when I checked the code I got  that it will be a very complex task since it should work with VersioningRequestProcessor or WriteCache to work properly. Do you have any suggestion or documentation on how to do that currectly?

**Comment by LaurenSpiegel** [comment]
@hosseinko, one  of our team members was playing around with swapping in memcached as a backend for metadata last week. His code should be helpful (though it is not a finished project yet)-- https://github.com/vrancurel/zenko-memcached-module

**Comment by hosseinko** [comment]
@LaurenSpiegel as I checked the code. the problem is that like LevelDB this code fetches all data from db and filter them by js. the main problem is that there are not sufficient data in files like MetadataFileServer.js to filter data in db layer. The parameters stay in \lib\metadata\bucketfile\backend.js and will be used in a callback to filter. In addition in this project VersionProcessorManager, WriteCache and WriteGatheringManager are not used. I think if I want to use data filtering in db layer for databases like mongodb or mysql I have to write backend, versioning and other related files again!

**Comment by LaurenSpiegel** [comment]
Hi,
@hosseinko, you are correct that the sample is a simplified implementation not taking advantage of write gathering. If you want to take advantage of the write gathering, you would have to reimplement the get, list and batch functions of the metadataAPI instead (e.g., get here: https://github.com/scality/Arsenal/blob/master/lib/storage/metadata/file/MetadataFileServer.js#L169). We have not tested this, but in theory it should work. @jonathan-gramain, thanks for the input on this.

Regarding fetching all data, we only filter the data with js for the listing call and we destroy the stream once you have received the requested list. From a quick googling, it looks like you can stream from mongo. Am I missing the problem?

**Comment by mutex007** [comment]
Could you advice if there is an API to read the keys and values as is from Level db with the current implementation without obviously having to shut down the server and using another script to read them or having to use the high level S3 Api to reconstruct the meta data. We plan on swapping the LevelDB backed MDServer with MongoRocks (MongoDB + RocksDB). Benefit been replication and the high availability we get from that setup.

**Comment by LaurenSpiegel** [comment]
@mutex007, we have high availability through [Zenko](https://github.com/scality/Zenko) and async replication is almost ready in our new [Backbeat](https://github.com/scality/backbeat) component which can all be deployed through Zenko. Does this get you what you need?

**Comment by mutex007** [comment]
HA of the main s3 server in our use case is taken care of. Our initial requirement is mainly to introduce a replicated backend for the MDServer. In this case, we will be running multiple MDServer instances all attached to the same backend. Each S3 api server distributed across different hosts will communicate with its own MDServer. Since all MDServers communicate with the same backend primary, the data is always consistent. If a host goes down, the load balancer simply does not send traffic to that node. In this case, there is always an MDServer and S3 Api server available. The next stage will be to repeat this step for the data server as well,

**Comment by LaurenSpiegel** [comment]
@mutex007, if you want to pull all of the keys and metadata values for the objects out of s3, you could modify the s3 code a bit so that the listing does not filter and then stream everything out that way on a per bucket basis. Note you would not be getting the bucket metadata that way.  In this file (https://github.com/scality/S3/blob/master/lib/metadata/wrapper.js) at line 177 we are parsing the listing but before that, the data has all of the metadata.  You would also have to change the way the data is parsed in the api directory so you just send back the whole thing. Does that get you closer to what you want?

**Comment by vrancurel** [comment]
@hosseinko we've just merged it, let us know your feedback !
