### ISSUE TITLE
InvalidURI on s3cmd's recursive option

### ISSUE THREAD

**Issue by DavidPineauScality** [scality/S3#83]
I was doing some manual tests on a fresh install, and noticed a weird behavior. I can do any kind of operation, but it looks like s3cmd's recursive operations are a no-go (or at least automatic removal of a bucket and its contents):

``` sh
# s3cmd -c s3cfg.mem-v4 -r rb s3://testbucket                                                                                                                                                                                                  
WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...
ERROR: S3 error: 400 (InvalidURI): Couldn't parse the specified URI.
```

Essentially, to produce this situation, you can run the following script, on a clean install (I was using S3 Auth's memory backend):

``` sh
# s3cmd -c s3cfg.mem-v4 mb s3://testbucket
# s3cmd -c s3cfg.mem-v4 put /etc/hosts s3://testbucket/hosts
# s3cmd -c s3cfg.mem-v4 rb -r s3://testbucket
```

**Comment by vrancurel** [comment]
It is probably because we don't support POST based batch deletes

**Comment by LaurenSpiegel** [comment]
@vrancurel, correct.  We do not support batch delete.

**Comment by joeharlan** [comment]
@LaurenSpiegel, would you be able to share when/if product management expects to have this feature implemented?

**Comment by LaurenSpiegel** [comment]
@joeharlan, it is targeted for September.

**Comment by GiorgioRegni** [comment]
Will be fixed by multi object delete.
