### ISSUE TITLE
Is there an option to create endpoint with a prefix

### ISSUE THREAD

**Issue by rom-stratoscale** [scality/S3#838]
I would like to run aws cli using:

aws s3api --endpoint-url=https://10.16.145.187/s3 --no-verify-ssl --debug create-bucket --bucket rom

and then rely on nginx to forward the request by matching the /s3 location.

Could not find any related documentation.

Thanks

**Comment by LaurenSpiegel** [comment]
Hi, @rom-stratoscale, unfortunately the path is included in the signature so you will get an authentication error if you strip the /s3 before sending to s3server. If you leave it in when sending to s3server, s3server will interpret the request as a put object (put object rom in bucket s3).

**Comment by rom-stratoscale** [comment]
@LaurenSpiegel  thanks. I managed to do some tricks with nginx config, to make it work without the prefix.
Closing.

**Comment by myntlabs** [comment]
Hi @romfreiman I have this exact same issue - would you mind please sharing the nginx magic you peformed? Cheers (i know it's been a long time lol)
