### ISSUE TITLE
Cannot run npm commands with open source version

### ISSUE THREAD

**Issue by mvaude** [scality/S3#839]
## Bug report information

Since `azure` backend has been implemented, it is not possible to run `npm start` and `npm run` without `azure` credentials.

### Steps to reproduce the issue

- install S3
- `npm start` or `npm test`

### Actual result

Error regarding `azure` missing credentials

### Expected result

Working smoothly

### Proposal

Make `azure` backend optional

### Current behavior

Having `azure` credentials looks mandatory

**Comment by LaurenSpiegel** [comment]
Fixed by https://github.com/scality/S3/pull/833
