### ISSUE TITLE
docker alpine and cloud server

### ISSUE THREAD

**Issue by gustavo-rios** [scality/S3#848]
This is not an 'issue'  just a comment.

I am currently testing cloudserver to use in my dev environment with SSL, since we use docker and Linux Alpine I wanted to check how this solution would behave in such environment since is mostly nodejs based and the underlying OS shouldn't make a difference, from my initial tests seems to be working, the benefit?  Docker image using Alpine is more than 100 MB less in size compared with current solution reducing storage footprint.

Changes were minimal.  changing the first line in docker-entrypoint from #!/bin/bash  to #!/bin/sh and then in Dockerfile starts with these lines and append the rest.

FROM node:6-alpine
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN apk update \
  && apk add --virtual .build-deps \
    python \
    git \
    build-base \
  && apk add jq openssl \
  && npm install --production \
  && npm cache clear \
  && apk del .build-deps \
  && rm -rf /var/cache/apk/* \
  && rm -rf ~/.node-gyp \
  && rm -rf /tmp/npm-*

**Comment by LaurenSpiegel** [comment]
Thanks for sharing, @gustavo-rios ! It should work fine.
