### ISSUE TITLE
Unable to mount scality/s3server metadata directory on Windows - IO error:  Invalid Argument

### ISSUE THREAD

**Issue by spillin** [scality/S3#857]
# Issue template

### Description

This issue is similar to [Issue #368 ](https://github.com/scality/S3/issues/368), but is limited to the metadata directory (on Windows).  I am trying to run an s3server container, and mount both data and metadata volumes from local directories.  The data directory works fine, but adding the metadata directory produces the following error, and the container fails to start:

<pre><code>events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: /usr/src/app/lib/../localMetadata/rootDB: Invalid argument
    at /usr/src/app/node_modules/levelup/lib/levelup.js:117:34
    at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
</code></pre>

### Steps to reproduce the issue

<pre><code>docker run -d --name s3server -e SSL=TRUE ENDPOINT=<endpoint> -p 8443:8000 -v //c/docker/data:/usr/
src/app/localData -v //c/docker/metadata:/usr/src/app/localMetadata -d --privilege
d=true --rm scality/s3server</code></pre>

### Actual result

Running this command produces the error above, and removing the metadata directory and running the command works as expected.

### Additional information: (Node.js version, Docker version, etc)
Node:  6.11.0
Docker: Version 17.06.0-ce-win19 (12801)

**Comment by rahulreddy** [comment]
Closing this as the issue is stale. Please let us know if the issue persists, we can help.

**Comment by fsc7** [comment]
I have the same situation with cloudserver latest version.
