### ISSUE TITLE
Signed URL Access to EC2(Amazon Linux) returns 403 Forbidden

### ISSUE THREAD

**Issue by shirade** [scality/S3#882]
### Description
I am running scality/s3server:latest on docker on EC2(Amazon Linux). If I do http request to signed url for `getObject` which is signed by aws-sdk(Javascript), I get 403 Forbidden. I cannot get why it happens if I check `docker logs`. Please help me.

### Steps to reproduce the issue
I am running scality/s3server:latest on docker on EC2(Amazon Linux).

```bash
$ docker run -d -p 8000:8000 scality/s3server:latest
$ s3cmd mb s3://sample
$ s3cmd put .bash_history s3://sample/
```

If I do http request to signed url for `getObject` which is signed by aws-sdk(Javascript), I get 403 Forbidden.

```javascript
var S3 = require('aws-sdk/clients/s3');
var client = new S3({
  endpoint: '127.0.0.1:8000',
  accessKeyId: 'accessKey1',
  secretAccessKey: 'verySecretKey1',
  s3ForcePathStyle: true,
  sslEnabled: false
});

client.getSignedUrl('getObject', {
    Bucket: 'sample',
    Key: '.bash_history',
    Expires: 15 * 60 // 900 sec
  }, console.log);
```

### Actual result
Then I do http request

```bash
$ curl 'http://127.0.0.1:8000/sample/.bash_profile?AWSAccessKeyId=accessKey1&Expires=10503544861&Signature=T1LC8xsf7OPyr5rCo44q0tL4mlM%3D'
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource></Resource><RequestId>f54267e60f4c9d98be1a</RequestId></Error>

$ docker logs s3server | tail
{"name":"S3","bucketName":"sample","objectKey":".bash_profile","bytesReceived":0,"bodyLength":0,"bytesSent":174,"clientIP":"::ffff:172.17.0.1","clientPort":36540,"httpMethod":"GET","httpURL":"/sample/.bash_profile?AWSAccessKeyId=accessKey1&Expires=10503544861&Signature=T1LC8xsf7OPyr5rCo44q0tL4mlM%3D","contentLength":0,"httpCode":403,"time":1503544878970,"req_id":"f54267e60f4c9d98be1a","elapsed_ms":1.483227,"level":"info","message":"responded with error XML","hostname":"34372aaf829a","pid":125}
```

I cannot understand why this happens from this message. What else can I check to solve this problem?

### Expected result

Expected result is getting the object file. 

**If I do this on my local Macbook Pro, I can get the object file.**

**Comment by nicolas2bert** [comment]
Hey @shirade - 

First, you can up your log level to `trace` in order to get more log informations.
To do so, use `LOG_LEVEL` environment variable:

`docker run -d --name s3server -p 8000:8000 -e LOG_LEVEL=trace scality/s3server`

[More info here](http://s3-server.readthedocs.io/en/latest/DOCKER/#log-level)

About your issue, it might be due to clock skew.
An easy test would be to increase the time the signed url is supposed to last.

Let me know how it goes :)

**Comment by dan-aksenov** [comment]
In my case it was really clock skew on test VM.
