### ISSUE TITLE
Issue mounting volumes

### ISSUE THREAD

**Issue by bill22152** [scality/S3#888]
When I start the docker with volumes to save data to a local volume with the following:

docker run -d \
--name s3server -p 8000:8000 \
-v /data1/Test2/DataPath:/usr/src/app/localData \
-v /data1/Test2/Metadata:/usr/src/app/localMetadata \
scality/s3server

## Results in
docker logs s3server

  binding.access(pathModule._makeLong(path), mode);
          ^
Error: EACCES: permission denied, access '/usr/src/app/lib/../localMetadata'
    at Error (native)
    at Object.fs.accessSync (fs.js:249:11)
    at MetadataFileServer.startServer (/usr/src/app/node_modules/arsenal/lib/storage/metadata/file/MetadataFileServer.js:124:12)
    at Object.<anonymous> (/usr/src/app/mdserver.js:17:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

I did try this with Env variables as well, they didn't seem to have any effect at all.
export S3DATAPATH="/data1/Test2/DataPath"
export S3METADATAPATH="/data1/Test2/Metadata" 
docker run -d \
--name s3server -p 8000:8000 \
scality/s3server

This didn't fail but it also didn't use the local volume either.

**Comment by LaurenSpiegel** [comment]
Hi @bill22152, does the user running the docker command have permissions for those paths? What operating system are you using? Note the capital letters might be an issue on mac -- https://docs.docker.com/docker-for-mac/osxfs/

**Comment by bill22152** [comment]
I'm running Docker on Fedora.

I checked the permissions for the target and I do have permissions
[root@s3storage data1]# ls -ld /data1/
drwxrwxrwx. 6 root root 4096 Aug 31 14:14 /data1/
[root@s3storage data1]# ls -ld /data1/Test2/
drwxrwxrwx. 5 scality scality 4096 Aug 31 14:30 /data1/Test2/
[root@s3storage data1]# ls -ld /data1/Test2/*
drwxrwxrwx. 2 scality scality 4096 Aug 31 14:14 /data1/Test2/DataPath
drwxrwxrwx. 2 scality scality 4096 Aug 31 14:14 /data1/Test2/Metadata
drwxr-xr-x. 2 scality scality 4096 Aug 31 14:30 /data1/Test2/ssl

I know its not secure, I'm just trying to get it to work.

**Comment by bill22152** [comment]
> node dataserver.js
fs.js:249
  binding.access(pathModule._makeLong(path), mode);
          ^
Error: EACCES: permission denied, access '/usr/src/app/lib/../localMetadata'
    at Error (native)
    at Object.fs.accessSync (fs.js:249:11)
    at MetadataFileServer.startServer (/usr/src/app/node_modules/arsenal/lib/storage/metadata/file/MetadataFileServer.js:124:12)
    at Object.<anonymous> (/usr/src/app/mdserver.js:17:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
npm info lifecycle s3@7.0.0~start_mdserver: Failed to exec start_mdserver script
npm ERR! Linux 4.12.8-300.fc26.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "start_mdserver"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! s3@7.0.0 start_mdserver: `node mdserver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.0.0 start_mdserver script 'node mdserver.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node mdserver.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
ERROR: "start_mdserver" exited with 1.
npm info lifecycle s3@7.0.0~start_dmd: Failed to exec start_dmd script
npm ERR! Linux 4.12.8-300.fc26.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "start_dmd"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! s3@7.0.0 start_dmd: `npm-run-all --parallel start_mdserver start_dataserver`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.0.0 start_dmd script 'npm-run-all --parallel start_mdserver start_dataserver'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel start_mdserver start_dataserver
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
ERROR: "start_dmd" exited with 1.
npm info lifecycle s3@7.0.0~start: Failed to exec start script
npm ERR! Linux 4.12.8-300.fc26.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! s3@7.0.0 start: `npm-run-all --parallel start_dmd start_s3server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the s3@7.0.0 start script 'npm-run-all --parallel start_dmd start_s3server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the s3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm-run-all --parallel start_dmd start_s3server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs s3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls s3
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by LaurenSpiegel** [comment]
@bill22152, a few things:
1) Will you please try running the "sestatus" command to see if selinux is enabled and report back to us?
2) Please also try to add ":Z" at the end of the mount options, like this: "-v /data1/Test2/DataPath:/usr/src/app/localData:Z -v /data1/Test2/Metadata:/usr/src/app/localMetadata:Z"
3) Please let us know which fedora version and which docker version you are using.

thanks

**Comment by bill22152** [comment]
The :Z worked...

[billf@s3storage DataPath]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      30

[billf@s3storage DataPath]$ mount | grep /data1
/dev/mapper/fedora-data on /data1 type ext4 (rw,relatime,seclabel,data=ordered)

**Comment by bill22152** [comment]
In lieu of addressing SELinux fixes the :Z is working so I can continue testing...

Thank you LaurenSpiegel

**Comment by bill22152** [comment]
[billf@s3storage lib]$ cat /etc/os-release 
NAME=Fedora
VERSION="26 (Server Edition)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Server Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=26
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=26
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Server Edition"
VARIANT_ID=server

**Comment by bill22152** [comment]
[billf@s3storage lib]$ docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      b5e3294/1.13.1
 Built:           Wed Aug 16 13:58:20 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      b5e3294/1.13.1
 Built:           Wed Aug 16 13:58:20 2017
 OS/Arch:         linux/amd64
 Experimental:    false
