### ISSUE TITLE
"details": {"serverSideEncryption": true}

### ISSUE THREAD

**Issue by bill22152** [scality/S3#894]
# Issue serverSideEncryption

in file "locationConfig.json":
    "us-east-1": {
        "type": "file",
        "legacyAwsBehavior": true,
        "details": {"serverSideEncryption": true}
    },

**Comment by LaurenSpiegel** [comment]
Please see http://s3-server.readthedocs.io/en/latest/ARCHITECTURE/#encryption

Let us know if that is unclear.
