### ISSUE TITLE
Data directory for buckets

### ISSUE THREAD

**Issue by sanster23** [scality/S3#898]
Hi, 
I am using Scality S3 server for internal code testing but I am not able to comprehend how actually the data is stored in backend, is the bucket equivalent to a folder. Can you clear a bit because i need to find the data that is being copied in the bucket?

**Comment by nicolas2bert** [comment]
Hi @sanster23, if you are using file backend (== default backend), when you start CloudServer it generates 3511 directories. 
Your object's data gets stored randomly in these directories.
Your objet's metadata gets stored in [leveldb](https://github.com/Level/levelup)
So no, in object storage, bucket is not equivalent to a folder. 

More information about object storage: http://www.scality.com/object-storage/

**Comment by sanster23** [comment]
Thanks for the response, i found the scality/arsenal logic which writes the data to disk. 
Would it be possible if instead of disk i put data to HDFS?

**Comment by nicolas2bert** [comment]
@sanster23, you are welcome, 

Yes, you can write your own HDFS data backend. 

- Here is where we start the file data backend server; you will also have to start your HDFS data backend here: https://github.com/scality/S3/blob/cac7450507b51f16310e1af7f2552164706506ea/dataserver.js

- Here is the datastore file for data file backend, you can use its logic to write your own: https://github.com/scality/Arsenal/blob/master/lib/storage/data/file/DataFileStore.js

- These PUT, GET and delete functions are called here:
https://github.com/scality/Arsenal/blob/master/lib/network/rest/RESTServer.js

Data stored in file-backend is not encrypted by default,
More information here: http://s3-server.readthedocs.io/en/latest/ARCHITECTURE/#encryption
