### ISSUE TITLE
Install fails on Ubuntu 17.04

### ISSUE THREAD

**Issue by gonzague** [scality/S3#902]
### Description

Cant install S3 on Ubuntu 17.04 

### Steps to reproduce the issue

I followed the instructions (git clone.. npm install..) but I get an error 

### Actual result

root@mymachine ~/S3 # npm install
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Permission denied (publickey).
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: fatal: Could not read from remote repository.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: 
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: Please make sure you have the correct access rights
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719: and the repository exists.

> diskusage@0.2.3 install /root/S3/node_modules/diskusage
> node-gyp rebuild

make: Entering directory '/root/S3/node_modules/diskusage/build'
  CXX(target) Release/obj.target/diskusage/src/main.o
  CXX(target) Release/obj.target/diskusage/src/diskusage_posix.o
  SOLINK_MODULE(target) Release/obj.target/diskusage.node
  COPY Release/diskusage.node
make: Leaving directory '/root/S3/node_modules/diskusage/build'
s3@7.0.0 /root/S3
├─┬ arsenal@7.0.1  (git://github.com/scality/Arsenal.git#e89395c42863c6f129de69c373311f7d6130f12a)
│ ├── async@2.1.5 
│ ├── diskusage@0.2.3 
│ └── uuid@3.1.0 
├── UNMET PEER DEPENDENCY eslint-plugin-react@^4.2.3
├─┬ utapi@7.0.0  (git://github.com/scality/utapi.git#394c1019bc4f3109344c2a72034effe461dca003)
│ └── async@2.5.0 
└─┬ vaultclient@7.0.0  (git://github.com/scality/vaultclient.git#2fe77c87934e0ab6c44aa537af058f0c26f0108a)
  ├── commander@2.9.0 
  └─┬ xml2js@0.4.17 
    └── xmlbuilder@4.2.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cdmiclient@github:scality/cdmiclient (node_modules/cdmiclient):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:scality/cdmiclient.git /root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-scality-cdmiclient-git-7531c719'...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Permission denied (publickey).
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fatal: Could not read from remote repository.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Please make sure you have the correct access rights
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: and the repository exists.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none was installed.

### Additional information: (Node.js version, Docker version, etc)
node -v
v6.11.3

npm -v
3.10.10

**Comment by LaurenSpiegel** [comment]
Would the server not start? Those warning should be ok.

**Comment by nicolas2bert** [comment]
@gonzague, if your server did not start, try with the required version:
npm -v 3.10.10
node -v 6.9.5
Don't forget to remove your node modules rm -r node_modules/ and re-install them. :)

If it still fails, you can try to remove the `optionalDependencies` section  in your s3/package.json 
```
"optionalDependencies": {
    "cdmiclient": "scality/cdmiclient"
},
```
More information here: http://s3-server.readthedocs.io/en/latest/GETTING_STARTED/#dependencies

Let us know.
