### ISSUE TITLE
authentication seems broken

### ISSUE THREAD

**Issue by samuellugassy** [scality/S3#912]
When using custom authdata.json with command for docker run:
```docker run -d --name s3server -p 8000:8000 -e ENDPOINT=s3.mylab.com -v ~/zenko/authdata.json:/usr/src/app/conf/authdata.json -v ~/zenko/data:/usr/src/app/localData -v  ~/zenko/metadata:/usr/src/app/localMetadata scality/s3server```
With the following custom authdata.json:
```# cat authdata.json 
{
    "accounts": [{
        "name": "Bart",
        "email": "sampleaccount1@sampling.com",
        "arn": "aws::iam:123456789012:root",
        "canonicalID": "79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be",
        "shortid": "123456789012",
        "keys": [{
            "access": "accessKey1",
            "secret": "verySecretKey1"
        }],
        "users": [{
            "name": "sam",
            "email": "samuel.lugassy@scality.com",
            "arn": "aws::iam:123456789013:sam",
            "keys": [{
                "access": "coolAccess",
                "secret": "grandeDetente"
            }]
         }, {
            "name": "backbeat",
            "email": "backbeat@scality.com",
            "arn": "aws::iam:123456789012:user/backbeat",
            "keys": [{
                "access": "accessKeyBackbeat",
                "secret": "verySecretKeyBackbeat"
            }]
        }]
    }, {
        "name": "Lisa",
        "email": "sampleaccount2@sampling.com",
        "arn": "aws::iam:accessKey2:user/Lisa",
        "canonicalID": "79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2bf",
        "shortid": "123456789012",
        "keys": [{
            "access": "accessKey2",
            "secret": "verySecretKey2"
        }]
    }, {
        "name": "Docker",
        "email": "sampleaccount3@sampling.com",
        "arn": "aws::iam:accessKeyDocker:user/Docker",
        "canonicalID": "sd359df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47eh3hd",
        "shortid": "123456789012",
        "keys": [{
            "access": "accessKeyDocker",
            "secret": "verySecretKeyDocker"
        }]
    }]
}
```
The container starts properly, 
however the Accesskey and secretKey written in the .aws/credentials file aren't taken into account.
Here is my credential file:
```
 >cat /Users/slugassy/.aws/credentials 
[default]
aws_access_key_id = lala
aws_secret_access_key = oulala
```
When I try listening a bucket with the following command:
```
$ aws s3  --endpoint http://s3.mylab.com:8000 ls s3://bucket1
2017-09-26 16:54:56        470 hosts
2017-09-26 17:15:02          0 hosts.equiv
```

I am able to list the bucket even though my credentials are wrong (the credentials file does not match any profile from the authdata.json).
Am I missing something ?

**Comment by nicolas2bert** [comment]
I was not able to replicate your issue.
Let's make sure that AWS S3 CLI is using `.aws/credentials` by running `aws s3  --endpoint http://s3.mylab.com:8000 ls s3://bucket1 --debug`

You should see something like this: `2017-09-26 10:26:37,602 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials`
If not, it means that AWS S3 CLI is using a different credential pair.

**Comment by samuellugassy** [comment]
Hi Nicolas,
Thanks a lot.
Indeed the debug showed that I was using the environment variables:
botocore.credentials - INFO - Found credentials in environment variables.
You can close the ticket.
Thanks
