### ISSUE TITLE
not git in node:4 base image

### ISSUE THREAD

**Issue by arthurlogilab** [scality/S3#92]
```
docker build .
[snip]
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

installing git (or using another FROM image) probably solves the problem.

**Comment by GiorgioRegni** [comment]
@nicolas2bert you were about to build using the Dockerfile on master, correct?

**Comment by nicolas2bert** [comment]
Yes, I just did and tested it. It should work now. @arthurlogilab @GiorgioRegni  @DavidPineauScality

**Comment by GiorgioRegni** [comment]
@nicolas2bert did you have to make changes to the Dockerfile?

**Comment by nicolas2bert** [comment]
Hey @arthurlogilab , 

To investigate, 

- Can you do `docker images | grep node` and send me the response.
- Which Docker version are you using?

Thanks,
Nicolas.

**Comment by arthurlogilab** [comment]
@nicolas2bert 

```
arthur@host:~$ docker images | grep node
node                                      4                   071009987a05        6 months ago        203.1 MB
node                                      4.2                 071009987a05        6 months ago        203.1 MB
arthur@host:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:54:25 2016
 OS/Arch:      linux/amd64
```

**Comment by nicolas2bert** [comment]
Hey @arthurlogilab , we checked and git is supposed to be in your node images.
Can you update your node image? 
`docker pull node:4.4 ` and retry your build.

Thanks.
Let me know,

Nicolas

**Comment by arthurlogilab** [comment]
@nicolas2bert ok, you seem to be right build-pack-deps has git it in https://github.com/docker-library/buildpack-deps/blob/e7534be05255522954f50542ebf9c5f06485838d/jessie/scm/Dockerfile sorry, my node images must be weird. Will rebuild it (sorry I never pull images from the hub).
