### ISSUE TITLE
Listing directory/ Failed

### ISSUE THREAD

**Issue by munavar89** [scality/S3#925]
1) On a Windows7 machine, installed Docker toolbox, Kitematic, Cyberduck.
2) On a docker quickstart terminal, executed the command "docker run -d --name s3server -p 8000:8000 scality/s3server".
3) On kitematic, searched for s3 scality server and clicked on create.
4) Now when I try to connect using cyberduck, it throws an error message Listing/ directory failed.

Attached the screenshots
![scality issue1](https://user-images.githubusercontent.com/32555018/31252119-cd9d3fc0-aa3d-11e7-9a3a-eab74675eefd.png)
![scality issue2](https://user-images.githubusercontent.com/32555018/31252118-cd918054-aa3d-11e7-975f-0d99fa110576.png)
![scality issue3](https://user-images.githubusercontent.com/32555018/31252120-cda9ff44-aa3d-11e7-99f2-873bee59f741.png)
![scality issue4](https://user-images.githubusercontent.com/32555018/31252121-cded5c62-aa3d-11e7-94bd-fc07df5203cd.png)

**Comment by LaurenSpiegel** [comment]
Please try http instead of https.

**Comment by munavar89** [comment]
Thanks for your reply.
I missed to Download the cyberduck S3 HTTP profile from
 https://svn.cyberduck.io/trunk/profiles/S3%20(HTTP).cyberduckprofile
now it works
