### ISSUE TITLE
Connections resets after some data is transferred

### ISSUE THREAD

**Issue by vladas-qstar** [scality/S3#94]
Can you help me with the Scality Server issue?
I can transfer small objects but larger object transfer fails. 

I am attaching tcp dump.
The S3 server is installed on Windows 64 laptop using docket and Hyper-V.
The client is Linux computer but local Windows client behaves the same way.

Thank you 

[scal.cap.gz](https://github.com/scality/S3/files/376592/scal.cap.gz)

**Comment by nicolas2bert** [comment]
Hey vladas-qstar,

-  Which S3 client tool (aws-sdk, s3cmd, cyberduck ... ) are you using to transfer your small/larger object?
- Can you send the log errors that you are receiving ?

Thanks,

Nicolas

**Comment by vladas-qstar** [comment]
Nicolas, 
Thank you for response.

I am using my own libcurl based client. 

But here is how s3cmd is behaving. Essentially 
it is throttling speed of transmission an that seems to allow to upload in 3 attempts.  

So I assume that this virtual  S3 server just can't accept data fast enough and reset socket.
 
./s3cmd -c /root/.s3cfg.s2 --signature-v2  put 00000000000001b0 s3://vladas1/data/0000/0000/0000/0000/00000000000001b3
00000000000001b0 -> s3://vladas1/data/0000/0000/0000/0000/00000000000001b3  [1 of 1]
 3932278 of 3932278   100% in    3s  1176.62 kB/s  failed
WARNING: Upload failed: /data/0000/0000/0000/0000/00000000000001b3 ()
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
00000000000001b0 -> s3://vladas1/data/0000/0000/0000/0000/00000000000001b3  [1 of 1]
 3932278 of 3932278   100% in    3s  1174.89 kB/s  failed
WARNING: Upload failed: /data/0000/0000/0000/0000/00000000000001b3 ()
WARNING: Retrying on lower speed (throttle=0.01)
WARNING: Waiting 6 sec...
00000000000001b0 -> s3://vladas1/data/0000/0000/0000/0000/00000000000001b3  [1 of 1]
 3932278 of 3932278   100% in    9s   388.78 kB/s  done

**Comment by nicolas2bert** [comment]
Can you show me how your s3configuration looks like ? (s3cfg.s2)

**Comment by vladas-qstar** [comment]
Here it is:

[default]
access_key = accessKey1
access_token =
add_encoding_exts =
add_headers =
bucket_location = US
ca_certs_file =
cache_file =
check_ssl_certificate = True
cloudfront_host = cloudfront.amazonaws.com
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = False
dry_run = False
enable_multipart = True
encoding = UTF-8
encrypt = False
expiry_date =
expiry_days =
expiry_prefix =
follow_symlinks = False
force = False
get_continue = False
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o\
 %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o\
 %(output_file)s %(input_file)s
gpg_passphrase =
guess_mime_type = True
host_base =  10.0.0.16:8000
#host_bucket = %(bucket)s.s3.amazonaws.com
host_bucket = 10.0.0.16:8000
human_readable_sizes = False
ignore_failed_copy = False
einvalidate_default_index_on_cf = False
invalidate_default_index_root_on_cf = True
invalidate_on_cf = False
list_md5 = False
log_target_prefix =
max_delete = -1
mime_type =
multipart_chunk_size_mb = 15
preserve_attrs = True
progress_meter = True
proxy_host =
proxy_port = 0
put_continue = False
recursive = False
recv_chunk = 4096
reduced_redundancy = False
restore_days = 1
secret_key = verySecretKey1
send_chunk = 4096
server_side_encryption = False
signature_v2 = True
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
urlencoding_mode = normal
use_https = False
use_mime_magic = True
verbosity = WARNING
website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
website_error =
website_index = index.html

Thank you

**Comment by nicolas2bert** [comment]
And what is the size of your file? The limit size before it fails?

**Comment by ThibaultRiviere** [comment]
I did a test, where is was putting a 1GO file without any issue and then i used the command line ```wondershaper``` for limit the bandwidth and i had the same error . 
```
  1703936 of 15728640    10% in    0s    22.39 MB/s  failed
WARNING: Upload failed: /1GO?partNumber=1&uploadId=e704e9d9c4e54b9c87c347665062d5c1 (timed out)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
```
This failure came after adding a socket_timeout in my s3cfg .
