### ISSUE TITLE
Terrafrom scenarios failures

### ISSUE THREAD

**Issue by rom-stratoscale** [scality/S3#950]
Hey,

I'm trying to run terraform 0.10.7 (latest) scenario (create bucket + object upload) vs the server, and it fails due to a 501 response from the unsupportedQueries (accelerate, logging, requestPayment and more).
Do you have any experience with it? Any suggested work around (except from removing the unsupportedQueries list)? Any plan to fix it in the future?

Thanks.

**Comment by LaurenSpiegel** [comment]
Hi @rom-stratoscale, I've never played with Terraform with s3server. Does it make an accelerate/logging/requestPayment call even if you do not set any of those features in your Terraform file? If you remove those api calls from your unsupportedQueries list you will likely get back a bucket listing response from s3server. Does Terraform proceed if that is the response it gets?

**Comment by LaurenSpiegel** [comment]
If that's the case, you could try changing the error here to errors.AccessDenied: https://github.com/scality/Arsenal/blob/master/lib/s3routes/routes.js#L31

**Comment by rom-stratoscale** [comment]
Nice!!! Will keep you posted. Thanks.

**Comment by rom-stratoscale** [comment]
@LaurenSpiegel from what I understand, the unimplemented flow does not reach the code you mentioned.
Anyhow, I changed https://github.com/scality/S3/blob/master/lib/utilities/validateQueryAndHeaders.js#L34 to return error.ok instead and all seems to be working.
Closing the issue.
