### ISSUE TITLE
Upload using HTTP POST

### ISSUE THREAD

**Issue by NamingException** [scality/S3#953]
Hi,

I've been trying to integrate scality/S3 server with the Signal application (server/android app).
I managed to make the attachments transmission functional using presigned urls generated by the signal server and the android app uses the PUT method to upload the file.

I've been having problems with the account avatar image functionality. The android app is using POST multipart/form-data to upload the new image with the following body:

AWS S3 Doc http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

```
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="acl"

private
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="key"

profiles/n_Zk5FoVPXsXSgx0pw4JHA
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="policy"

eyAiZXhwaXJhdGlvbiI6ICIyMDE3LTEwLTIwVDA3OjUwOjMxLjU5MFoiLAogICJjb25kaXRpb25zIjogWwogICAgeyJidWNrZXQiOiAic2lnbmFsLXByb2ZpbGVzIn0sCiAgICB7ImtleSI6ICJwcm9maWxlcy9uX1prNUZvVlBYc1hTZ3gwcHc0SkhBIn0sCiAgICB7ImFjbCI6ICJwcml2YXRlIn0sCiAgICBbInN0YXJ0cy13aXRoIiwgIiRDb250ZW50LVR5cGUiLCAiIl0sCgogICAgeyJ4LWFtei1jcmVkZW50aWFsIjogIlM5VDNISjBONVFDSzJUTU9VM0ZQLzIwMTcxMDIwL3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QifSwKICAgIHsieC1hbXotYWxnb3JpdGhtIjogIkFXUzQtSE1BQy1TSEEyNTYifSwKICAgIHsieC1hbXotZGF0ZSI6ICIyMDE3MTAyMFQwNzIwMzFaIiB9CiAgXQp9
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="Content-Type"

image/jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x-amz-algorithm"

AWS4-HMAC-SHA256
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x-amz-credential"

S9T3HJ0N5QCK2TMOU3FP/20171020/us-east-1/s3/aws4_request
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x-amz-date"

20171020T072031Z
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="x-amz-signature"

85b655a4cccd2aab2b77be1202a6b2b3c7b01bb6c7da6774efed988535d0373a
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="signal-app-ic-launcher.png"
Content-Type: image/png


------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

On the s3 server I get the following log:

```
{"name":"S3","clientIP":"::ffff:213.177.1.218","clientPort":51296,"httpMethod":"POST","httpURL":"/signal-profiles","time":1508502036463,"req_id":"f02b04c70540b7b82596","level":"info","message":"received request","hostname":"5956e1742ed0","pid":157}
{"name":"S3","bucketName":"signal-profiles","bytesReceived":89817,"bodyLength":89817,"method":"routePOST","time":1508502036466,"req_id":"f02b04c70540b7b82596","level":"debug","message":"routing request","hostname":"5956e1742ed0","pid":157}
{"name":"S3","bucketName":"signal-profiles","bytesReceived":89817,"bodyLength":89817,"errCode":{"code":501,"description":"A header you provided implies functionality that is not implemented.","NotImplemented":true},"time":1508502036466,"req_id":"f02b04c70540b7b82596","level":"trace","message":"sending error xml response","hostname":"5956e1742ed0","pid":157}
{"name":"S3","bucketName":"signal-profiles","bytesReceived":89817,"bodyLength":89817,"bytesSent":231,"clientIP":"::ffff:213.177.1.218","clientPort":51296,"httpMethod":"POST","httpURL":"/signal-profiles","httpCode":501,"time":1508502036468,"req_id":"f02b04c70540b7b82596","elapsed_ms":5.045503,"level":"info","message":"responded with error XML","hostname":"5956e1742ed0","pid":157}
```

Can you tell me if upload using http post is supported?

**Comment by LaurenSpiegel** [comment]
Unfortunately, we do not support browser-based upload using post at this time.

**Comment by martyn-w** [comment]
Hi @NamingException,

I've been facing the same problem: I could not make browser-based uploads (with signed URLs) like your example above work in Scality S3.

I've got round this by trying [minio](https://github.com/minio/minio) instead. Minio supports most of the S3 protocol (including browser-based uploads and signed URLs). However it doesn't seem to support DNS-style buckets (http://mybucket.localhost/) and so you must update your code/application to use path based buckets (http://server/mybucket). If you are using the AWS SDK, make sure you initialise your client with the `force_path_style: true` option, e.g. in Ruby:

```
require 'aws-sdk'
s3 = Aws::S3::Client.new(endpoint: 'http://minio:9000', force_path_style: true)
s3.create_bucket(bucket: "foo")
```

Hope that helps,

Martyn.

**Comment by raphaelcosta** [comment]
@LaurenSpiegel there is any workaround for that?

**Comment by LaurenSpiegel** [comment]
@raphaelcosta, have you tried forcing a put request? See https://stackoverflow.com/questions/8054165/using-put-method-in-html-form/37125568

**Comment by raphaelcosta** [comment]
@LaurenSpiegel thanks! I changed to PUT and now received that `SOAP requests must be made over an HTTPS connection.`

**Comment by LaurenSpiegel** [comment]
@raphaelcosta, I just tried it myself and it is not going to work because we are not parsing the request to "unwrap" that it is actually a put. 

Can you do a post to your own server and then a request from your server that uses put to s3server? Or put an on click event for your button submit that then uses javascript/jquery to do a put?
