### ISSUE TITLE
s3server fails on multipy part upload

### ISSUE THREAD

**Issue by rom-stratoscale** [scality/S3#960]
Hey,
Sometimes, I get the following error in s3server logs:
{"name":"S3","bucketName":"tenderbrown","objectKey":"dreamy_fermat","bytesReceived":0,"bodyLength":0,"rawError":{"code":"ETIMEDOUT","info":"operation put timed out"},"error":"Callback function \"bound _call\" ti
med out.","errorStack":"Error: Callback function \"bound _call\" timed out.\n    at Timeout.timeoutCallback [as _onTimeout] (/usr/src/app/node_modules/arsenal/node_modules/async/dist/async.js:4724:21)\n    at on
timeout (timers.js:386:11)\n    at tryOnTimeout (timers.js:250:5)\n    at Timer.listOnTimeout (timers.js:214:5)","time":1508786680781,"req_id":"2ba9f156354ba5b9f5b7","level":"error","message":"error putting obje
ct","hostname":"stratonode_c1n7.node.strato","pid":167}
{"name":"S3","bucketName":"tenderbrown","objectKey":"dreamy_fermat","bytesReceived":0,"bodyLength":0,"implName":"bucketfile","error":{"code":500,"description":"We encountered an internal error. Please try again.
","InternalError":true},"time":1508786680781,"req_id":"2ba9f156354ba5b9f5b7","level":"debug","message":"error from metadata","hostname":"stratonode_c1n7.node.strato","pid":167}
{"name":"S3","bucketName":"tenderbrown","objectKey":"dreamy_fermat","bytesReceived":0,"bodyLength":0,"error":{"code":500,"description":"We encountered an internal error. Please try again.","InternalError":true},
"time":1508786680781,"req_id":"2ba9f156354ba5b9f5b7","level":"error","message":"error from metadata","hostname":"stratonode_c1n7.node.strato","pid":167}

Then, I guess the client retries and proceeds (not 100% sure though).
But, once trying to delete a bucket, I get 
  File "/usr/lib/python2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (MPUinProgress) when calling the DeleteBucket operation: The bucket you tried to delete has an ongoing multipart upload.

And indeed, I can see that there are multipy part uploads that are stuck:
~> aws s3api --endpoint-url=https://cluster --no-verify-ssl  list-multipart-uploads --bucket tenderbrown
{
    "Uploads": [
        {
            "Initiator": {
                "DisplayName": "default", 
                "ID": "a8b5109032814ad6844e757d96c33468"
            }, 
            "Initiated": "2017-10-23T19:22:29.549Z", 
            "UploadId": "0dbae18e12b34ec3b3b48f996c99ab0d", 
            "StorageClass": "STANDARD", 
            "Key": "dreamy_fermat", 
            "Owner": {
                "DisplayName": "default", 
                "ID": "a8b5109032814ad6844e757d96c33468"
            }
        }, 
        {
            "Initiator": {
                "DisplayName": "default", 
                "ID": "a8b5109032814ad6844e757d96c33468"
            }, 
            "Initiated": "2017-10-23T19:24:10.765Z", 
            "UploadId": "44dcf3039cd64bc9b824155bf4584aee", 
            "StorageClass": "STANDARD", 
            "Key": "dreamy_fermat", 
            "Owner": {
                "DisplayName": "default", 
                "ID": "a8b5109032814ad6844e757d96c33468"
            }
        }, 
        {
            "Initiator": {
                "DisplayName": "default", 
                "ID": "a8b5109032814ad6844e757d96c33468"
            }, 
            "Initiated": "2017-10-23T19:23:33.549Z", 
            "UploadId": "bef5ff26b2b241bc8a5d3c2aee48091d", 
            "StorageClass": "STANDARD", 
            "Key": "dreamy_fermat", 
            "Owner": {
                "DisplayName": "default", 
                "ID": "a8b5109032814ad6844e757d96c33468"
            }
        }, 
        {
            "Initiator": {
                "DisplayName": "default", 
                "ID": "a8b5109032814ad6844e757d96c33468"
            }, 
            "Initiated": "2017-10-23T19:21:59.473Z", 
            "UploadId": "c9e89ab974b34408b28e94f0d5580f59", 
            "StorageClass": "STANDARD", 
            "Key": "dreamy_fermat", 
            "Owner": {
                "DisplayName": "default", 
                "ID": "a8b5109032814ad6844e757d96c33468"
            }
        }, 
......
What is the reason for those failure?

Thanks,
Rom

**Comment by LaurenSpiegel** [comment]
Hi, @rom-stratoscale please try increasing the timeout here and see if you still have the problem:
https://github.com/scality/Arsenal/blob/master/lib/network/rpc/rpc.js#L16

The timeout is occurring when doing the put to our metadata service. Are you running the s3 server on the same machine as the metadata server? I assume you are unless you are using this:
https://github.com/scality/zenko

**Comment by rom-stratoscale** [comment]
@LaurenSpiegel hey again :)
It's strange - It's all a single container - so I would not expect 3s timeout to happen.
Can it be affected by the storage latency of the host? Or its only an api call that saves data in memory?
Also, why does it leak after timeout?? I think there is a retry that succeeds afterwards. So it's also strange.
Anyhow, trying and will see if it reproduces.

**Comment by rom-stratoscale** [comment]
Oh. it's 30 sec.... anyhow, lets make it 90.

**Comment by LaurenSpiegel** [comment]
It's writing the metadata to leveldb. So perhaps it is delayed if you are trying to make multiple connections to leveldb?

**Comment by rom-stratoscale** [comment]
Seems that increasing the timeout to 90s worked. 
Yes, Im running a load that uploads in parallel big objects.
