### ISSUE TITLE
Confusing output when location doesn't exist

### ISSUE THREAD

**Issue by LaureVergeron** [scality/S3#965]
### When trying to put to an undefined location, you get "done" from s3cmd before "ERROR" from CloudServer

I tried to put to a location called "azure" when my location name is "azure-test", and got the following output:
```
~/S3Server$ s3cmd put /etc/hosts s3://multibackend/azurehosts --add-header x-amz-meta-scal-location-constraint:azure
upload: '/etc/hosts' -> 's3://multibackend/azurehosts'  [1 of 1]
 330 of 330   100% in    0s    83.29 kB/s  done
ERROR: S3 error: 400 (InvalidArgument): Object Location Error - Your object location "azure"is not  in your location config - Please update.
```
The situation is handled properly, though: there is no `azurehosts` object when I list the `multibackend` bucket. It's just weird that I would get a "done" from s3cmd and then an "ERROR" from CloudServer.
Also, this doesn't happen is I try to create a bucket to a region that doesn't exist - I get an error straight away, which is great:
```
~/S3Server$s3cmd mb s3://multibackendazure --region=azure
ERROR: S3 error: 400 (InvalidLocationConstraint): value of the location you are attempting to set - azure - is not listed in the locationConstraint config
```
Is the object behaviour a known behaviour?

**Comment by LaurenSpiegel** [comment]
You are getting a "done" message just on the s3cmd client upload. You would get the same if the bucket did not exist or other errors.
